GLOBAL.setmetatable(env,{__index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end})

--------------------------<公告类信息>--------------------------
GLOBAL.ANNOUNCE_ANTLION_TRIBUTE = "那会暂时让它安静..."

GLOBAL.ANNOUNCE_KLAUS_CALLFORHELP = "它在求救！"
GLOBAL.ANNOUNCE_KLAUS_UNCHAINED = "它的链条松开了！"
GLOBAL.ANNOUNCE_KLAUS_ENRAGE = "现在没有办法打败它了！！"
GLOBAL.ANNOUNCE_MOON_DEVICE = "[月亮虹吸器] 需要20天重新聚集能量"
GLOBAL.ANNOUNCE_KLAUS_SACK = "[克劳斯包] 或许你应该30天后再来"
GLOBAL.WRONGPIECE = "那不太对吧"

STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_ATTACK = "动手打！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_ELECTRICATTACK = "我带的是正电！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_MOISTUREIMMUNITY = "干的像薇克巴顿的讲义！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_PLAYERABSORPTION = "我现在感觉安全多了！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_SLEEPRESISTANCE = "顿时觉得神清气爽，再也不累了！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATTACH_BUFF_WORKEFFECTIVENESS = "生产力提高！"

--------------------------<档案馆/中庭互动语音>--------------------------
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ARCHIVE_NO_POWER = "没有足够的能量启动这个装置"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ARCHIVE_NEW_KNOWLEDGE = "我学到了新的知识！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ARCHIVE_OLD_KNOWLEDGE = "这个我已经知道了"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ATRIUM_DESTABILIZING = "大门开始不稳定了！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_RUINS_RESET = "遗迹开始重置了！"
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_GATE_ON = "大门已激活"

--------------------------<蚁狮模块>--------------------------
STRINGS.CHARACTERS.GENERIC.ANNOUNCE_ANTLION_SINKHOLE = "地面在震动！"
 
--------------------------<strings信息>--------------------------
STRINGS.NAMES.ALTERGUARDIAN_PHASE1 = "天体英雄"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALTERGUARDIAN_PHASE1 = "你会为破坏科学付出代价！"

STRINGS.NAMES.ALTERGUARDIAN_PHASE2 = "天体英雄"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALTERGUARDIAN_PHASE2 = "我想我激怒它了……"

STRINGS.NAMES.ALTERGUARDIAN_PHASE3 = "天体英雄"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALTERGUARDIAN_PHASE3 = "它现在一定生气了！"

STRINGS.NAMES.ALTERGUARDIAN_PHASE3DEAD = "被击败的天体英雄"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALTERGUARDIAN_PHASE3DEAD = "应该找个人过去戳一下……这样才能确定"

STRINGS.NAMES.ALTERGUARDIAN_PHASE3DEADORB = "天体英雄"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALTERGUARDIAN_PHASE3DEADORB = "它死了吗？那股神秘的力量好像还在它附近游荡"

STRINGS.NAMES.ALTERGUARDIAN_PHASE3TRAP = "启迪凝视"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALTERGUARDIAN_PHASE3TRAP = "经过不懈测试，我可以确认它们让我想打盹"

STRINGS.NAMES.ALTERGUARDIAN_PHASE2SPIKE = "月光玻璃突刺"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALTERGUARDIAN_PHASE2SPIKE = "你已经表明了你的观点！"

STRINGS.NAMES.ALTERGUARDIANHAT = "启迪之冠"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ALTERGUARDIANHAT = "它让我看到了无限可能……"

STRINGS.NAMES.MOONGLASS = "月亮碎片"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASS = "它非常锋利"

STRINGS.NAMES.MOONGLASS_CHARGED = "灌注月亮碎片"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASS_CHARGED = "我应该在能量耗尽前为它找到科学的用途！"

STRINGS.NAMES.MOONGLASS_ROCK = "月光玻璃岩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASS_ROCK = "月光凝结成的玻璃状岩石"

STRINGS.NAMES.MOONROCKNUGGET = "月岩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONROCKNUGGET = "那块石头来自月亮"

STRINGS.NAMES.MOONROCKSEED = "天体宝珠"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONROCKSEED = "靠近它会提供新的制作配方"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONROCKSEED_ACTIVATED = "它似乎充满了知识"

STRINGS.NAMES.GLASSCUTTER = "玻璃刀"
STRINGS.RECIPE_DESC.GLASSCUTTER = "尖端武器"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSCUTTER = "我真的不是打架的料"

STRINGS.NAMES.MOONGLASSAXE = "月光玻璃斧"
STRINGS.RECIPE_DESC.MOONGLASSAXE = "脆弱而有效"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASSAXE = "我把它做的非常好用"

STRINGS.NAMES.CHESSPIECE_GUARDIANPHASE3_STONE = "天体英雄雕像"
STRINGS.NAMES.CHESSPIECE_GUARDIANPHASE3_MOONGLASS = "天体英雄雕像"

STRINGS.NAMES.CHESSPIECE_ROOK = "大理石战车"
STRINGS.NAMES.CHESSPIECE_KNIGHT = "大理石战马"
STRINGS.NAMES.CHESSPIECE_BISHOP = "大理石主教"
STRINGS.RECIPE_DESC.CHESSPIECE_ROOK = "大理石雕刻成的\n战车形状"
STRINGS.RECIPE_DESC.CHESSPIECE_KNIGHT = "大理石雕刻成的\n马匹形状"
STRINGS.RECIPE_DESC.CHESSPIECE_BISHOP = "大理石雕刻成的\n主教形状"

STRINGS.NAMES.MOON_DEVICE = "月亮虹吸器"
STRINGS.NAMES.MOON_DEVICE_CONSTRUCTION1 = "未完成的实验"
STRINGS.RECIPE_DESC.MOON_DEVICE_CONSTRUCTION1 = "有疯狂科学的认可\n但从未测试过"

STRINGS.NAMES.TURF_METEOR = "月球环形山地皮"
STRINGS.RECIPE_DESC.TURF_METEOR = "月球表面的月坑"
STRINGS.RECIPE_DESC.TURF_PEBBLEBEACH = "满是鹅卵石的海滩"
STRINGS.RECIPE_DESC.TURF_SHELLBEACH = "散落着贝壳的海滩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_METEOR = "一块月球地面"

STRINGS.NAMES.OASISLAKE = "绿洲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OASISLAKE = {
   EMPTY = "干的像一块骨头",
   GENERIC = "这是海市蜃楼吗？",
}

STRINGS.NAMES.SUCCULENT_PLANT = "多肉植物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_PLANT = "那里有芦荟"
 
STRINGS.NAMES.SUCCULENT_PICKED = "多肉植物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_PICKED = "我能吃那个，但我不想吃"

STRINGS.NAMES.SUCCULENT_POTTED = "多肉盆栽" 
STRINGS.RECIPE_DESC.SUCCULENT_POTTED = "塞进陶盆的漂亮\n多肉植物" 
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUCCULENT_POTTED = "塞进陶盆的漂亮多肉植物"

STRINGS.NAMES.ANTLION = "蚁狮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTLION = "这会给我的世界带来破坏..."

STRINGS.NAMES.SANDBLOCK = "沙堡"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDBLOCK = "真是坚持不懈！"

STRINGS.NAMES.SANDSPIKE = "沙刺"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SANDSPIKE = "我原本会被刺穿的！"

STRINGS.NAMES.ANTLIONTRINKET = "沙滩玩具"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ANTLIONTRINKET = "有人可能对此感兴趣"

STRINGS.NAMES.GLASSSPIKE = "玻璃狼牙棒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSSPIKE = "我还没有被刺穿时的记忆"

STRINGS.NAMES.GLASSBLOCK = "玻璃沙堡"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GLASSBLOCK = "这份科学送给你"

--邪天翁
STRINGS.NAMES.MALBATROSS = "邪天翁"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MALBATROSS = "禽鸟巨兽！"

STRINGS.NAMES.MALBATROSS_FEATHER = "邪天翁羽毛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MALBATROSS_FEATHER = "从大鸟身上拔下的漂亮羽毛"

STRINGS.NAMES.MALBATROSS_FEATHERED_WEAVE = "羽毛帆布"
STRINGS.RECIPE_DESC.MALBATROSS_FEATHERED_WEAVE = "精美的羽毛布料"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MALBATROSS_FEATHERED_WEAVE = "我在织羽毛被！"

STRINGS.NAMES.MALBATROSS_BEAK = "邪天翁喙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MALBATROSS_BEAK = "闻起来有鱼腥味"

STRINGS.NAMES.MALBATROSS_SAIL = "飞翼风帆"
STRINGS.RECIPE_DESC.MALBATROSS_SAIL = "像海鸟一样航向\n深蓝"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MALBATROSS_SAIL = "展翅远航！"

--月台
STRINGS.NAMES.MOONBASE = "月亮石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONBASE = "中间有个洞，好像可以扔东西进去"

STRINGS.NAMES.MOON_TREE_BLOSSOM = "月树花"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_TREE_BLOSSOM = "从月树上飘落的花瓣"

STRINGS.NAMES.MOONBUTTERFLY = "月娥"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONBUTTERFLY = "一只散发着柔和光芒的月蛾"

STRINGS.NAMES.MOONBUTTERFLYWINGS = "月娥翅膀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONBUTTERFLYWINGS = "轻盈而又神秘"

--月岛
STRINGS.NAMES.BATHBOMB = "浴球"
STRINGS.RECIPE_DESC.BATHBOMB = "泡个温泉放松一下"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BATHBOMB = "泡个温泉放松一下"

STRINGS.NAMES.ROCK_AVOCADO_FRUIT = "石果"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_AVOCADO_FRUIT = "像石头一样硬的果子"

STRINGS.NAMES.ROCK_AVOCADO_FRUIT_RIPE = "成熟的石果"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_AVOCADO_FRUIT_RIPE = "撬开后露出了里面的果肉"

STRINGS.NAMES.ROCK_AVOCADO_FRUIT_RIPE_COOKED = "烤石果"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_AVOCADO_FRUIT_RIPE_COOKED = "烤熟后更香了"

STRINGS.NAMES.ROCK_AVOCADO_FRUIT_SPROUT = "石果苗"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_AVOCADO_FRUIT_SPROUT = "小苗从果子里钻了出来"

STRINGS.NAMES.ROCK_AVOCADO_FRUIT_SPROUT_SAPLING = "石果树苗"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_AVOCADO_FRUIT_SPROUT_SAPLING = "很快就能长成一棵石果树了"

STRINGS.NAMES.ROCK_AVOCADO_BUSH = "石果树"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ROCK_AVOCADO_BUSH = "长着石头果实的灌木"

STRINGS.NAMES.DUG_ROCK_AVOCADO_BUSH = "挖起的石果树"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_ROCK_AVOCADO_BUSH = "可以重新种下去"

STRINGS.NAMES.SAPLING_MOON = "月岛树枝"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SAPLING_MOON = "在月光下生长的树枝"

STRINGS.NAMES.MOON_FISSURE = "天体裂隙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_FISSURE = "散发着神秘能量的裂隙"

STRINGS.NAMES.MOONSPIDER = "破碎蜘蛛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONSPIDER = "被月亮能量扭曲的蜘蛛"

STRINGS.NAMES.MOONSPIDERDEN = "破碎蜘蛛巢"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONSPIDERDEN = "里面不知道有多少蜘蛛"

STRINGS.NAMES.MOONSPIDER_SPIKE = "蜘蛛刺"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONSPIDER_SPIKE = "很尖很危险"

--月岛雕像
STRINGS.NAMES.MOON_ALTAR_IDOL = "月亮伟人雕像"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_IDOL = "一块神秘的雕像碎片"
STRINGS.NAMES.MOON_ALTAR_GLASS = "月亮玻璃雕像"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_GLASS = "一块神秘的雕像碎片"
STRINGS.NAMES.MOON_ALTAR_SEED = "月亮种子雕像"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_SEED = "一块神秘的雕像碎片"
STRINGS.NAMES.MOON_ALTAR_CROWN = "月亮雕像王冠"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_CROWN = "一块神秘的雕像碎片"
STRINGS.NAMES.MOON_ALTAR_WARD = "月亮结界雕像"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_WARD = "一块神秘的雕像碎片"
STRINGS.NAMES.MOON_ALTAR_ICON = "月亮圣像雕像"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_ICON = "一块神秘的雕像碎片"
STRINGS.NAMES.MOON_ALTAR_ROCK_IDOL = "伟人岩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_ROCK_IDOL = "也许内部藏有什么东西"
STRINGS.NAMES.MOON_ALTAR_ROCK_GLASS = "玻璃岩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_ROCK_GLASS = "也许内部藏有什么东西"
STRINGS.NAMES.MOON_ALTAR_ROCK_SEED = "种子岩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_ROCK_SEED = "也许内部藏有什么东西"

STRINGS.NAMES.MOON_ALTAR = "天体祭坛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR = "散发着强大月亮能量的祭坛"
STRINGS.NAMES.MOON_ALTAR_WIP = "未完成的天体祭坛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_WIP = "祭坛还需要更多的碎片"

STRINGS.NAMES.MOON_ALTAR_ASTRAL = "远古天体祭坛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_ASTRAL = "散发着来自远古的月亮能量"
STRINGS.NAMES.MOON_ALTAR_ASTRAL_WIP = "未完成的远古祭坛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_ASTRAL_WIP = "远古祭坛还需要更多的碎片"

STRINGS.NAMES.MOON_ALTAR_COSMIC = "天体王冠祭坛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_ALTAR_COSMIC = "散发着宇宙能量的王冠祭坛"

STRINGS.NAMES.MOON_TREE = "月树"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_TREE = "在月光照耀下生长的树木"

STRINGS.NAMES.OPALSTAFF = "唤月者法杖"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OPALSTAFF = "科学方面证明，宝石在棍子的顶部看起来更耀眼"

STRINGS.NAMES.OPALPRECIOUSGEM = "彩虹宝石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OPALPRECIOUSGEM = "充满了彩虹的魔力"

STRINGS.NAMES.GARGOYLE_HOUND = "可疑的月岩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GARGOYLE_HOUND = "我不喜欢它看我的眼神"

STRINGS.NAMES.GARGOYLE_WEREPIG = "可疑的月岩"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GARGOYLE_WEREPIG = "它看起来栩栩如生"

STRINGS.NAMES.DRAGONFLY2 = "熔岩龙蝇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFLY2 = "那是一只熔岩龙蝇！"
 
STRINGS.NAMES.LAVA_POND = "熔岩池"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVA_POND = "好烫好烫！"
STRINGS.NAMES.LAVA_POND_ROCK = "岩石"
STRINGS.NAMES.SCORCHED_SKELETON = "易碎骨骼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCORCHED_SKELETON = "真可怕"
STRINGS.NAMES.BURNT_MARSH_BUSH = "尖刺灌木"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BURNT_MARSH_BUSH = "又尖又烫"
STRINGS.NAMES.LAVAE = "熔岩虫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAE = "好烫！"
STRINGS.NAMES.LAVAE_EGG = "熔岩虫卵"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAE_EGG = "一颗滚烫的蛋"
STRINGS.NAMES.LAVAE_EGG_CRACKED = "孵化中的熔岩虫卵"
STRINGS.NAMES.LAVAE_COCOON = "冷冻虫卵"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAE_COCOON = "冷却下来了"
STRINGS.NAMES.LAVAE_PET = "超级可爱岩浆虫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAE_PET = "我的小伙伴"
STRINGS.NAMES.LAVAE_TOOTH = "岩浆虫尖牙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LAVAE_TOOTH = "一颗蛋牙！"

STRINGS.NAMES.DRAGONFLYFURNACE = "龙鳞火炉"
STRINGS.RECIPE_DESC.DRAGONFLYFURNACE = "永远不会熄灭的暖炉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DRAGONFLYFURNACE = "永远不会熄灭的暖炉"

STRINGS.NAMES.KLAUS = "克劳斯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KLAUS = "那究竟是什么东西！"

STRINGS.NAMES.KLAUSSACKKEY = "麋鹿茸"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KLAUSSACKKEY = "对一个鹿角来说这真是太花俏了"

STRINGS.NAMES.KLAUS_SACK = "赃物袋"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.KLAUS_SACK = "我们绝对应该打开那东西"

STRINGS.NAMES.DEER = "无眼鹿"
STRINGS.NAMES.DEER_RED = "无眼鹿"
STRINGS.NAMES.DEER_BIUE = "无眼鹿"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEER = "它是不是盯着我？…不，我猜没有"

STRINGS.NAMES.DEER_GEMMED = "无眼鹿"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEER_GEMMED = "它被那头野兽控制着！"

STRINGS.NAMES.DEER_ANTLER = "鹿角"
STRINGS.NAMES.DEER_ANTLER1 = "鹿角"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEER_ANTLER = "掉下来正常吗？"

--暗影三基佬
STRINGS.NAMES.SHADOW_KNIGHT = "暗影骑士"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOW_KNIGHT = "暗影化的骑士"
STRINGS.NAMES.SHADOW_BISHOP = "暗影主教"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOW_BISHOP = "暗影化的主教"
STRINGS.NAMES.SHADOW_ROOK = "暗影战车"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOW_ROOK = "暗影化的战车"
STRINGS.NAMES.SHADOWHEART = "暗影心房"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOWHEART = "科学的力量肯定使它恢复生气了..."

STRINGS.NAMES.SCULPTURE_KNIGHTHEAD = "可疑的大理石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCULPTURE_KNIGHTHEAD = "我不喜欢它看我的眼神"
STRINGS.NAMES.SCULPTURE_BISHOPHEAD = "可疑的大理石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCULPTURE_BISHOPHEAD = "它看起来有点奇怪"
STRINGS.NAMES.SCULPTURE_ROOKNOSE = "可疑的大理石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCULPTURE_ROOKNOSE = "它看起来很重"

STRINGS.NAMES.SCULPTURE_KNIGHTBODY = "大理石雕像"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCULPTURE_KNIGHTBODY = "一尊骑士雕像"
STRINGS.NAMES.SCULPTURE_BISHOPBODY = "大理石雕像"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCULPTURE_BISHOPBODY = "一尊主教雕像"
STRINGS.NAMES.SCULPTURE_ROOKBODY = "大理石雕像"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCULPTURE_ROOKBODY = "一尊战车雕像"

STRINGS.NAMES.HOTSPRING = "温泉"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HOTSPRING = {
  BOMBED = "简单的化学反应而已",
  EMPTY = "那我就等等它再变满吧",
  GENERIC = "能泡下这身疲倦的身骨该多好",
  GLASS = "水在月光下凝结成玻璃，这就是科学",
}

--食物buff
STRINGS.NAMES.PEPPER = "辣椒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PEPPER = "好一个火辣辣的辣椒"
STRINGS.NAMES.PEPPER_COOKED = "烤辣椒"
STRINGS.NAMES.PEPPER_SEEDS = "辣椒种子"

STRINGS.NAMES.ONION = "洋葱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ONION = "看起来很脆"
STRINGS.NAMES.ONION_COOKED = "烤洋葱"
STRINGS.NAMES.ONION_SEEDS = "洋葱种子"

STRINGS.NAMES.PEPPERPOPPER = "爆炒填馅辣椒"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PEPPERPOPPER = "这么一大口！"

STRINGS.NAMES.FROGFISHBOWL = "蓝带鱼排"
STRINGS.NAMES.FRESHFRUITCREPES = "鲜果可丽饼"
STRINGS.NAMES.BONESOUP = "骨头汤"
STRINGS.NAMES.DRAGONCHILISALAD = "辣龙椒沙拉"
STRINGS.NAMES.GLOWBERRYMOUSSE = "发光浆果慕斯"
STRINGS.NAMES.VOLTGOATJELLY = "伏特羊肉冻"

STRINGS.NAMES.LEAFLOAF = "叶肉糕"
STRINGS.NAMES.LEAFYMEATBURGER = "素食堡"
STRINGS.NAMES.LEAFYMEATSOUFFLE = "果冻沙拉"
STRINGS.NAMES.MEATYSALAD = "牛肉绿叶菜"


--------------------------<fox特殊检视>--------------------------
STRINGS.CHARACTERS.FOX = STRINGS.CHARACTERS.FOX or {}
STRINGS.CHARACTERS.FOX.DESCRIBE = STRINGS.CHARACTERS.FOX.DESCRIBE or {}

--天体英雄
STRINGS.CHARACTERS.FOX.DESCRIBE.ALTERGUARDIAN_PHASE1 = "你会为破坏科学付出代价！"
STRINGS.CHARACTERS.FOX.DESCRIBE.ALTERGUARDIAN_PHASE2 = "我好像激怒它了……"
STRINGS.CHARACTERS.FOX.DESCRIBE.ALTERGUARDIAN_PHASE3 = "它现在一定很生气"
STRINGS.CHARACTERS.FOX.DESCRIBE.ALTERGUARDIAN_PHASE3DEAD = "要不要戳一下……就一下"
STRINGS.CHARACTERS.FOX.DESCRIBE.ALTERGUARDIAN_PHASE3DEADORB = "它死了吗？奇怪的能量还在周围飘着"
STRINGS.CHARACTERS.FOX.DESCRIBE.ALTERGUARDIAN_PHASE3TRAP = "这个东西让人想打瞌睡"
STRINGS.CHARACTERS.FOX.DESCRIBE.ALTERGUARDIAN_PHASE2SPIKE = "好痛！"
STRINGS.CHARACTERS.FOX.DESCRIBE.ALTERGUARDIANHAT = "它让我看到了无限可能"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONGLASS = "好锋利"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONGLASS_CHARGED = "在能量消失之前得用掉它"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONGLASS_ROCK = "月光玻璃岩石"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONROCKNUGGET = "从月亮上掉下来的石头"
STRINGS.CHARACTERS.FOX.DESCRIBE.GLASSCUTTER = "尖端武器"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONGLASSAXE = "脆弱但有效"
STRINGS.CHARACTERS.FOX.DESCRIBE.TURF_METEOR = "一块月球地面"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONBASE = "中间有个洞，可以放东西进去"
STRINGS.CHARACTERS.FOX.DESCRIBE.OPALSTAFF = "宝石在棍子上面果然最好看"
STRINGS.CHARACTERS.FOX.DESCRIBE.GARGOYLE_HOUND = "它看我的眼神让我不舒服"
STRINGS.CHARACTERS.FOX.DESCRIBE.GARGOYLE_WEREPIG = "它看起来就像真的一样"
STRINGS.CHARACTERS.FOX.DESCRIBE.DRAGONFLY2 = "那是只熔岩龙蝇！"
--蚁狮
STRINGS.CHARACTERS.FOX.DESCRIBE.ANTLION = "它想从我这里得到什么"
STRINGS.CHARACTERS.FOX.DESCRIBE.SANDBLOCK = "真是坚持不懈"
STRINGS.CHARACTERS.FOX.DESCRIBE.SANDSPIKE = "差点就被刺穿了"
STRINGS.CHARACTERS.FOX.DESCRIBE.ANTLIONTRINKET = "沙滩玩具，也许有人会想要这个"
STRINGS.CHARACTERS.FOX.DESCRIBE.GLASSSPIKE = "还没被刺穿的记忆"
STRINGS.CHARACTERS.FOX.DESCRIBE.GLASSBLOCK = "科学，送给你"
STRINGS.CHARACTERS.FOX.DESCRIBE.OASISLAKE = {
    EMPTY = "干得像骨头一样",
    GENERIC = "是海市蜃楼吗？",
}
STRINGS.CHARACTERS.FOX.DESCRIBE.SUCCULENT_PLANT = "那里有芦荟"
STRINGS.CHARACTERS.FOX.DESCRIBE.SUCCULENT_PICKED = "能吃，但我不想吃"
STRINGS.CHARACTERS.FOX.DESCRIBE.SUCCULENT_POTTED = "塞进花盆里的多肉植物"
--邪天翁
STRINGS.CHARACTERS.FOX.DESCRIBE.MALBATROSS = "好大一只鸟！"
STRINGS.CHARACTERS.FOX.DESCRIBE.MALBATROSS_FEATHER = "从大鸟身上拔下来的漂亮羽毛"
STRINGS.CHARACTERS.FOX.DESCRIBE.MALBATROSS_FEATHERED_WEAVE = "漂亮的羽毛布料"
STRINGS.CHARACTERS.FOX.DESCRIBE.MALBATROSS_BEAK = "闻起来有鱼腥味"
STRINGS.CHARACTERS.FOX.DESCRIBE.MALBATROSS_SAIL = "展翅远航！"
--联机龙蝇
STRINGS.CHARACTERS.FOX.DESCRIBE.LAVAE = "好烫！"
STRINGS.CHARACTERS.FOX.DESCRIBE.LAVAE_EGG = "熔岩虫的卵"
STRINGS.CHARACTERS.FOX.DESCRIBE.LAVAE_EGG_CRACKED = "蛋正在孵化"
STRINGS.CHARACTERS.FOX.DESCRIBE.LAVAE_COCOON = "被冻住的熔岩虫"
STRINGS.CHARACTERS.FOX.DESCRIBE.LAVAE_PET = "超级可爱的熔岩虫"
STRINGS.CHARACTERS.FOX.DESCRIBE.LAVAE_TOOTH = "熔岩虫的尖牙"
STRINGS.CHARACTERS.FOX.DESCRIBE.DRAGONFLYFURNACE = "龙鳞火炉，好暖和"
--克劳斯
STRINGS.CHARACTERS.FOX.DESCRIBE.KLAUS = "那到底是什么东西！"
STRINGS.CHARACTERS.FOX.DESCRIBE.KLAUSSACKKEY = "好花哨的鹿角"
STRINGS.CHARACTERS.FOX.DESCRIBE.KLAUS_SACK = "一定要打开看看"
STRINGS.CHARACTERS.FOX.DESCRIBE.DEER = "它在盯着我吗？……不，应该没有"
STRINGS.CHARACTERS.FOX.DESCRIBE.DEER_GEMMED = "它被那头野兽控制着"
STRINGS.CHARACTERS.FOX.DESCRIBE.DEER_ANTLER = "掉下来正常吗？"
--暗影三基佬
STRINGS.CHARACTERS.FOX.DESCRIBE.SHADOW_KNIGHT = "暗影骑士"
STRINGS.CHARACTERS.FOX.DESCRIBE.SHADOW_BISHOP = "暗影主教"
STRINGS.CHARACTERS.FOX.DESCRIBE.SHADOW_ROOK = "暗影战车"
STRINGS.CHARACTERS.FOX.DESCRIBE.SHADOWHEART = "暗影心房"
--温泉
STRINGS.CHARACTERS.FOX.DESCRIBE.HOTSPRING = {
    BOMBED = "简单的化学反应",
    EMPTY = "等它再装满吧",
    GENERIC = "好想泡一泡",
    GLASS = "水在月光下凝结成了玻璃",
}
--食物
STRINGS.CHARACTERS.FOX.DESCRIBE.PEPPER = "火辣辣的辣椒"
STRINGS.CHARACTERS.FOX.DESCRIBE.ONION = "看起来很脆"
STRINGS.CHARACTERS.FOX.DESCRIBE.PEPPERPOPPER = "好大一口！"
--国际象棋雕像
STRINGS.CHARACTERS.FOX.DESCRIBE.CHESSPIECE_ROOK = {
    GENERIC = "比看起来重",
    STRUGGLE = "棋子自己在动！",
}
STRINGS.CHARACTERS.FOX.DESCRIBE.CHESSPIECE_KNIGHT = {
    GENERIC = "是匹马",
    STRUGGLE = "棋子自己在动！",
}
STRINGS.CHARACTERS.FOX.DESCRIBE.CHESSPIECE_BISHOP = {
    GENERIC = "是个石头主教",
    STRUGGLE = "棋子自己在动！",
}

--暗影织影者
STRINGS.CHARACTERS.FOX.DESCRIBE.STALKER = "骨架和暗影融合在了一起！"
STRINGS.CHARACTERS.FOX.DESCRIBE.STALKER_ATRIUM = "为什么它要这么大？"
STRINGS.CHARACTERS.FOX.DESCRIBE.STALKER_MINION = "会咬到脚踝！"
STRINGS.CHARACTERS.FOX.DESCRIBE.FOSSIL_STALKER = {
    COMPLETE = "它活了！……哦不，没有",
    FUNNY = "直觉告诉我哪里不对",
    GENERIC = "还缺一些碎片",
}
STRINGS.CHARACTERS.FOX.DESCRIBE.FOSSIL_PIECE = "科学的骨头！拼起来看看吧"
STRINGS.CHARACTERS.FOX.DESCRIBE.ATRIUM_GATE = {
    CHARGING = "它在积蓄能量",
    COOLDOWN = "需要时间恢复，我也是",
    DESTABILIZING = "大门在晃动",
    OFF = "主要部分还是完好的",
    ON = "回到正常运转了",
}
STRINGS.CHARACTERS.FOX.DESCRIBE.ATRIUM_KEY = "有能量从里面散发出来"

-- 补充通用检视（暗影织影者）
STRINGS.NAMES.STALKER = "织影者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STALKER = "骨架和暗影融合在了一起！"
STRINGS.NAMES.STALKER_ATRIUM = "远古织影者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STALKER_ATRIUM = "为什么它要这么大？"
STRINGS.NAMES.STALKER_MINION = "织影者仆从"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.STALKER_MINION = "会咬到脚踝！"
STRINGS.NAMES.FOSSIL_STALKER = "化石织影者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FOSSIL_STALKER = {
    COMPLETE = "它活了！……哦不，没有",
    FUNNY = "直觉告诉我哪里不对",
    GENERIC = "还缺一些碎片",
}
STRINGS.NAMES.FOSSIL_PIECE = "化石碎片"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FOSSIL_PIECE = "科学的骨头！拼起来看看吧"
STRINGS.NAMES.ATRIUM_GATE = "远古大门"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ATRIUM_GATE = {
    CHARGING = "它在积蓄能量",
    COOLDOWN = "需要时间恢复，我也是",
    DESTABILIZING = "大门在晃动",
    OFF = "主要部分还是完好的",
    ON = "回到正常运转了",
}
STRINGS.NAMES.ATRIUM_KEY = "远古钥匙"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ATRIUM_KEY = "有能量从里面散发出来"
STRINGS.NAMES.SHADOWCHANNELER = "暗影通灵者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOWCHANNELER = "它在召唤什么东西"
STRINGS.NAMES.SHADOWMETEOR = "暗影流星"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOWMETEOR = "天上掉下来的暗影"
STRINGS.NAMES.GESTALT = "远行者"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GESTALT = "散发着纯净的光芒"
STRINGS.NAMES.MOONHOUND = "月蜘蛛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONHOUND = "被月亮能量扭曲的猎犬"
STRINGS.NAMES.MOONPIG = "月猪"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONPIG = "它看起来变了个样"
STRINGS.NAMES.OCEANTREE_PILLAR = "水中木"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANTREE_PILLAR = "长在水里的树"
STRINGS.NAMES.OCEANVINE = "海藤"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.OCEANVINE = "缠住一切的海中藤蔓"

--月岛沿海生物
STRINGS.NAMES.LIGHTCRAB = "光蟹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIGHTCRAB = "散发着柔和月光的螃蟹"

STRINGS.NAMES.TRAP_STARFISH = "绊线海星"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TRAP_STARFISH = "踩上去会被刺到"

STRINGS.NAMES.DUG_TRAP_STARFISH = "挖起的绊线海星"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_TRAP_STARFISH = "还算安全的处理方式"

STRINGS.NAMES.DEAD_SEA_BONES = "海洋枯骨"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DEAD_SEA_BONES = "不知道在这里躺了多久"

STRINGS.NAMES.PURPLEMOONEYE = "紫色月眼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.PURPLEMOONEYE = "一颗紫色的月亮宝石"
STRINGS.NAMES.BLUEMOONEYE = "蓝色月眼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLUEMOONEYE = "一颗蓝色的月亮宝石"
STRINGS.NAMES.REDMOONEYE = "红色月眼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.REDMOONEYE = "一颗红色的月亮宝石"
STRINGS.NAMES.ORANGEMOONEYE = "橙色月眼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ORANGEMOONEYE = "一颗橙色的月亮宝石"
STRINGS.NAMES.YELLOWMOONEYE = "黄色月眼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.YELLOWMOONEYE = "一颗黄色的月亮宝石"
STRINGS.NAMES.GREENMOONEYE = "绿色月眼"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GREENMOONEYE = "一颗绿色的月亮宝石"

STRINGS.NAMES.MOONGLASS_STALACTITE1 = "月玻璃钟乳石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASS_STALACTITE1 = "月光凝结成了钟乳石的形状"
STRINGS.NAMES.MOONGLASS_STALACTITE2 = "月玻璃钟乳石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASS_STALACTITE2 = "月光凝结成了钟乳石的形状"
STRINGS.NAMES.MOONGLASS_STALACTITE3 = "月玻璃钟乳石"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOONGLASS_STALACTITE3 = "月光凝结成了钟乳石的形状"

STRINGS.NAMES.FRUITDRAGON = "火龙果"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FRUITDRAGON = "长在温泉边的奇异果实"

STRINGS.NAMES.CARRAT = "胡萝卜鼠"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARRAT = "有着胡萝卜外表的奇怪小动物"

STRINGS.NAMES.CARRAT_PLANTED = "种下的胡萝卜"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CARRAT_PLANTED = "它把自己埋起来了"

STRINGS.NAMES.LIGHTFLIER_FLOWER = "光飞虫花"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIGHTFLIER_FLOWER = "散发着柔和月光的奇妙植物"

STRINGS.NAMES.LIGHTFLIER = "光飞虫"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LIGHTFLIER = "一只追逐光的小飞虫"

STRINGS.NAMES.LUNAR_GRAZER = "月辔"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.LUNAR_GRAZER = "被月亮能量吸引而来的温顺生物"

--FOX专属语音（月岛新增）
STRINGS.CHARACTERS.FOX.DESCRIBE.BATHBOMB = "泡个温泉放松一下"
STRINGS.CHARACTERS.FOX.DESCRIBE.ROCK_AVOCADO_FRUIT = "像石头一样的果子"
STRINGS.CHARACTERS.FOX.DESCRIBE.ROCK_AVOCADO_FRUIT_RIPE = "里面的果肉露出来了"
STRINGS.CHARACTERS.FOX.DESCRIBE.ROCK_AVOCADO_FRUIT_RIPE_COOKED = "烤一下更好吃"
STRINGS.CHARACTERS.FOX.DESCRIBE.ROCK_AVOCADO_FRUIT_SPROUT = "小苗钻出来了"
STRINGS.CHARACTERS.FOX.DESCRIBE.ROCK_AVOCADO_FRUIT_SPROUT_SAPLING = "快点长大吧"
STRINGS.CHARACTERS.FOX.DESCRIBE.ROCK_AVOCADO_BUSH = "石果灌木"
STRINGS.CHARACTERS.FOX.DESCRIBE.DUG_ROCK_AVOCADO_BUSH = "换个地方种吧"
STRINGS.CHARACTERS.FOX.DESCRIBE.SAPLING_MOON = "月下生长的树枝"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOON_FISSURE = "散发着神秘的能量"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONSPIDER = "被月亮扭曲的蜘蛛"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONSPIDERDEN = "好多蜘蛛在里面"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONSPIDER_SPIKE = "好尖啊"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOON_TREE = "月下生长的树木"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOON_TREE_BLOSSOM = "飘落的月树花瓣"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOON_ALTAR = "好强大的月亮能量"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOON_ALTAR_ASTRAL = "远古的月亮能量在流动"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOON_ALTAR_COSMIC = "宇宙能量在闪耀"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONBUTTERFLY = "好漂亮的月蛾"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONBUTTERFLYWINGS = "月蛾的翅膀"
STRINGS.CHARACTERS.FOX.DESCRIBE.SHADOWMETEOR = "暗影从天上掉下来了"
STRINGS.CHARACTERS.FOX.DESCRIBE.GESTALT = "散发着纯净光芒"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONHOUND = "变异的猎犬"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONPIG = "它变了样"
STRINGS.CHARACTERS.FOX.DESCRIBE.OCEANTREE_PILLAR = "长在水里的树"
STRINGS.CHARACTERS.FOX.DESCRIBE.OCEANVINE = "缠人的海藤"
--月岛沿海生物
STRINGS.CHARACTERS.FOX.DESCRIBE.LIGHTCRAB = "好漂亮的发光螃蟹"
STRINGS.CHARACTERS.FOX.DESCRIBE.TRAP_STARFISH = "踩上去会被刺到哦"
STRINGS.CHARACTERS.FOX.DESCRIBE.DUG_TRAP_STARFISH = "这样安全多了"
STRINGS.CHARACTERS.FOX.DESCRIBE.DEAD_SEA_BONES = "躺了好久吧"
STRINGS.CHARACTERS.FOX.DESCRIBE.PURPLEMOONEYE = "紫色的月亮宝石"
STRINGS.CHARACTERS.FOX.DESCRIBE.BLUEMOONEYE = "蓝色的月亮宝石"
STRINGS.CHARACTERS.FOX.DESCRIBE.REDMOONEYE = "红色的月亮宝石"
STRINGS.CHARACTERS.FOX.DESCRIBE.ORANGEMOONEYE = "橙色的月亮宝石"
STRINGS.CHARACTERS.FOX.DESCRIBE.YELLOWMOONEYE = "黄色的月亮宝石"
STRINGS.CHARACTERS.FOX.DESCRIBE.GREENMOONEYE = "绿色的月亮宝石"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONGLASS_STALACTITE1 = "月光钟乳石"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONGLASS_STALACTITE2 = "月光钟乳石"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOONGLASS_STALACTITE3 = "月光钟乳石"
STRINGS.CHARACTERS.FOX.DESCRIBE.FRUITDRAGON = "长在温泉边的果实"
STRINGS.CHARACTERS.FOX.DESCRIBE.CARRAT = "好像一根胡萝卜"
STRINGS.CHARACTERS.FOX.DESCRIBE.CARRAT_PLANTED = "它把自己藏起来了"
STRINGS.CHARACTERS.FOX.DESCRIBE.LIGHTFLIER = "追着光跑的小虫子"
STRINGS.CHARACTERS.FOX.DESCRIBE.LIGHTFLIER_FLOWER = "好漂亮的花，还会发光"
STRINGS.CHARACTERS.FOX.DESCRIBE.LUNAR_GRAZER = "月亮的食草动物"

--------------------------<月岛地皮>--------------------------
STRINGS.NAMES.TURF_METEOR = "月亮环形山地皮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_METEOR = "散发着月亮气息的焦土"
STRINGS.CHARACTERS.FOX.DESCRIBE.TURF_METEOR = "踩上去凉凉的"

STRINGS.NAMES.TURF_PEBBLEBEACH = "卵石海滩地皮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_PEBBLEBEACH = "海滩上的卵石很硌脚"
STRINGS.CHARACTERS.FOX.DESCRIBE.TURF_PEBBLEBEACH = "想光脚走可不行哦"

STRINGS.NAMES.TURF_SHELLBEACH = "贝壳海滩地皮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_SHELLBEACH = "这里的沙子混着碎贝壳"
STRINGS.CHARACTERS.FOX.DESCRIBE.TURF_SHELLBEACH = "能听到大海的声音"

--------------------------<DST 额外地皮>--------------------------
STRINGS.NAMES.TURF_ARCHIVE = "远古石工地皮"
STRINGS.RECIPE_DESC.TURF_ARCHIVE = "来自未封印档案馆的\n古老石材"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_ARCHIVE = "来自未封印档案馆的古老石材"
STRINGS.CHARACTERS.FOX.DESCRIBE.TURF_ARCHIVE = "很古老的样子"

STRINGS.NAMES.TURF_FUNGUS_MOON = "月真菌地皮"
STRINGS.RECIPE_DESC.TURF_FUNGUS_MOON = "散发着诡异的月光\n踩上去软软的"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_FUNGUS_MOON = "散发着诡异的月光"
STRINGS.CHARACTERS.FOX.DESCRIBE.TURF_FUNGUS_MOON = "踩上去软软的"

STRINGS.NAMES.TURF_MONKEY_GROUND = "猴岛地皮"
STRINGS.RECIPE_DESC.TURF_MONKEY_GROUND = "猴子们踩出来的地面\n有股香蕉味"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_MONKEY_GROUND = "猴子们踩出来的地面"
STRINGS.CHARACTERS.FOX.DESCRIBE.TURF_MONKEY_GROUND = "有股香蕉味"

--------------------------<DST 洞穴地皮>--------------------------
STRINGS.NAMES.TURF_VENT = "排气口地皮"
STRINGS.RECIPE_DESC.TURF_VENT = "洞穴中冒着热气的\n排气口地面"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VENT = "地面在冒着热气"
STRINGS.CHARACTERS.FOX.DESCRIBE.TURF_VENT = "热乎乎的"

STRINGS.NAMES.TURF_VAULT = "宝库地皮"
STRINGS.RECIPE_DESC.TURF_VAULT = "远古宝库中的\n精致石材"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TURF_VAULT = "宝库里的地面"
STRINGS.CHARACTERS.FOX.DESCRIBE.TURF_VAULT = "看起来很值钱"



--------------------------<猴岛内容>--------------------------
STRINGS.NAMES.MONKEY = "猴子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEY = "一只调皮的小猴子"
STRINGS.CHARACTERS.FOX.DESCRIBE.MONKEY = "离我的东西远点！"

STRINGS.NAMES.MONKEYBARREL = "猴子桶"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYBARREL = "猴子们从里面钻出来"
STRINGS.CHARACTERS.FOX.DESCRIBE.MONKEYBARREL = "原来它们住在这里面"

STRINGS.NAMES.MONKEYHUT = "猴子窝"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYHUT = "猴子们的简陋住处"
STRINGS.CHARACTERS.FOX.DESCRIBE.MONKEYHUT = "看起来随时会塌"

STRINGS.NAMES.MONKEYPILLAR = "猴子图腾柱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYPILLAR = "刻着猴子图案的石柱"
STRINGS.CHARACTERS.FOX.DESCRIBE.MONKEYPILLAR = "雕刻得还挺精致"

STRINGS.NAMES.MONKEYTAIL = "猴尾草"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEYTAIL = "形状像猴子尾巴的植物"
STRINGS.CHARACTERS.FOX.DESCRIBE.MONKEYTAIL = "好像猴子尾巴"

STRINGS.NAMES.POWDERMONKEY = "火药猴"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.POWDERMONKEY = "背着一桶火药的猴子！"
STRINGS.CHARACTERS.FOX.DESCRIBE.POWDERMONKEY = "离它远点！"

STRINGS.NAMES.BANANABUSH = "香蕉丛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BANANABUSH = "长着香蕉的灌木丛"
STRINGS.CHARACTERS.FOX.DESCRIBE.BANANABUSH = "好多香蕉！"

STRINGS.NAMES.CAVE_BANANA_TREE = "洞穴香蕉树"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAVE_BANANA_TREE = "在洞穴里顽强生长的香蕉树"
STRINGS.CHARACTERS.FOX.DESCRIBE.CAVE_BANANA_TREE = "洞穴里也能长香蕉"

STRINGS.NAMES.MONKEY_SMALLHAT = "小猴帽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MONKEY_SMALLHAT = "一顶小帽子"
STRINGS.CHARACTERS.FOX.DESCRIBE.MONKEY_SMALLHAT = "谁会戴这个？"

STRINGS.NAMES.CUTLESS = "海盗短剑"
STRINGS.RECIPE_DESC.CUTLESS = "海盗用的短剑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CUTLESS = "一把锋利的短剑"
STRINGS.CHARACTERS.FOX.DESCRIBE.CUTLESS = "看起来挺锋利的"

--------------------------<月蘑菇群系>--------------------------
STRINGS.NAMES.MUSHTREE_MOON = "月亮蘑菇树"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHTREE_MOON = "在月光下变异的蘑菇树"
STRINGS.CHARACTERS.FOX.DESCRIBE.MUSHTREE_MOON = "好大的蘑菇"

STRINGS.NAMES.MUSHTREE_MOONSPORE = "月蘑菇孢子"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHTREE_MOONSPORE = "月亮蘑菇树飘落的孢子"
STRINGS.CHARACTERS.FOX.DESCRIBE.MUSHTREE_MOONSPORE = "飘来飘去的孢子"

STRINGS.NAMES.MOON_MUSHROOM = "月蘑菇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MOON_MUSHROOM = "散发着柔和月光的蘑菇"
STRINGS.CHARACTERS.FOX.DESCRIBE.MOON_MUSHROOM = "会发光的蘑菇"

STRINGS.NAMES.CAVELIGHTMOON = "月光洞穴灯"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CAVELIGHTMOON = "照亮洞穴的月光植物"
STRINGS.CHARACTERS.FOX.DESCRIBE.CAVELIGHTMOON = "好亮"

STRINGS.NAMES.MUSHGNOME = "蘑菇地精"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHGNOME = "一只可爱的蘑菇小人"
STRINGS.CHARACTERS.FOX.DESCRIBE.MUSHGNOME = "好可爱的小蘑菇"

STRINGS.NAMES.GROTTO_POOL_BIG = "玻璃绿洲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GROTTO_POOL_BIG = "地下洞穴中的美丽水池"
STRINGS.CHARACTERS.FOX.DESCRIBE.GROTTO_POOL_BIG = "好漂亮的水池"

STRINGS.NAMES.GROTTO_POOL_SMALL = "小玻璃绿洲"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GROTTO_POOL_SMALL = "洞穴中的小型水池"
STRINGS.CHARACTERS.FOX.DESCRIBE.GROTTO_POOL_SMALL = "小水池"

STRINGS.NAMES.GROTTO_POOL_MOONGLASS = "月玻璃池"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GROTTO_POOL_MOONGLASS = "可以采集月玻璃的水池"
STRINGS.CHARACTERS.FOX.DESCRIBE.GROTTO_POOL_MOONGLASS = "水里有月亮碎片"

STRINGS.NAMES.GROTTO_WATERFALL_BIG = "大瀑布"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GROTTO_WATERFALL_BIG = "洞穴中壮观的瀑布"
STRINGS.CHARACTERS.FOX.DESCRIBE.GROTTO_WATERFALL_BIG = "好壮观"

STRINGS.NAMES.GROTTO_WATERFALL_SMALL = "小瀑布"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.GROTTO_WATERFALL_SMALL = "洞穴中的小瀑布"
STRINGS.CHARACTERS.FOX.DESCRIBE.GROTTO_WATERFALL_SMALL = "水声好好听"

--------------------------<毒菌蛤蟆>--------------------------
STRINGS.NAMES.TOADSTOOL = "毒菌蛤蟆"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.TOADSTOOL = "好大一只蘑菇！"
STRINGS.CHARACTERS.FOX.DESCRIBE.TOADSTOOL = "超级大蘑菇！"

STRINGS.NAMES.TOADSTOOL_CAP = "毒菌蛤蟆"
STRINGS.NAMES.TOADSTOOL_CAP_DARK = "毒菌蛤蟆"
STRINGS.NAMES.TOADSTOOL_HOLE = "洞穴"

STRINGS.NAMES.SPORECLOUD = "孢子云"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPORECLOUD = "一团有毒的孢子"
STRINGS.CHARACTERS.FOX.DESCRIBE.SPORECLOUD = "别吸进去！"

STRINGS.NAMES.MUSHROOMBOMB = "炸弹蘑菇"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOMBOMB = "一朵蘑菇云正在生成！"
STRINGS.CHARACTERS.FOX.DESCRIBE.MUSHROOMBOMB = "要炸了！"

STRINGS.NAMES.SPOREBOMB = "孢子炸弹"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SPOREBOMB = "它在释放孢子"
STRINGS.CHARACTERS.FOX.DESCRIBE.SPOREBOMB = "孢子到处都是"

STRINGS.NAMES.MUSHROOMSPROUT = "孢子帽"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOMSPROUT = "从地里冒出来的蘑菇"
STRINGS.CHARACTERS.FOX.DESCRIBE.MUSHROOMSPROUT = "地上冒出了蘑菇"

STRINGS.NAMES.CANARY = "金丝雀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CANARY = {
    GENERIC = "一只黄色的小鸟",
    HELD = "我不会压到你的，对吧？",
}
STRINGS.CHARACTERS.FOX.DESCRIBE.CANARY = {
    GENERIC = "一只黄色的小鸟",
    HELD = "我不会压到你的~",
}

STRINGS.NAMES.FEATHER_CANARY = "金丝雀羽毛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FEATHER_CANARY = "一根金丝雀的羽毛"
STRINGS.CHARACTERS.FOX.DESCRIBE.FEATHER_CANARY = "金丝雀的羽毛"

STRINGS.NAMES.CANARY_POISONED = "中毒金丝雀"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.CANARY_POISONED = "它可能是好的。"
STRINGS.CHARACTERS.FOX.DESCRIBE.CANARY_POISONED = "这只鸟看起来不太好"

STRINGS.NAMES.SCARECROW = "稻草人"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SCARECROW = {
    GENERIC = "穿着时髦的秋季新款。",
    BURNING = "有人在烧稻草人！",
    BURNT = "稻草人被烧毁了！",
}
STRINGS.CHARACTERS.FOX.DESCRIBE.SCARECROW = {
    GENERIC = "一个稻草人，穿着还挺时髦",
    BURNING = "着火了！",
    BURNT = "被烧掉了...",
}
STRINGS.RECIPE_DESC.SCARECROW = "展示所有最新秋季时装。"

STRINGS.NAMES.SHROOM_SKIN = "蘑菇皮"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHROOM_SKIN = "疣，都是疣！"
STRINGS.CHARACTERS.FOX.DESCRIBE.SHROOM_SKIN = "蘑菇的皮"

STRINGS.NAMES.MUSHROOM_LIGHT = "蘑菇灯"
STRINGS.RECIPE_DESC.MUSHROOM_LIGHT = "任何蘑菇的\n完美添加物。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOM_LIGHT = "一盏发光的蘑菇灯"
STRINGS.CHARACTERS.FOX.DESCRIBE.MUSHROOM_LIGHT = "蘑菇做的灯，好漂亮"

STRINGS.NAMES.MUSHROOM_LIGHT2 = "菌伞灯"
STRINGS.RECIPE_DESC.MUSHROOM_LIGHT2 = "灵感来自熔岩灯\n的科学。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOM_LIGHT2 = "一盏更精致的蘑菇灯"
STRINGS.CHARACTERS.FOX.DESCRIBE.MUSHROOM_LIGHT2 = "这个更好看！"

STRINGS.NAMES.MUSHROOMHAT = "蘑菇帽"
STRINGS.NAMES.RED_MUSHROOMHAT = "红蘑菇帽"
STRINGS.NAMES.GREEN_MUSHROOMHAT = "绿蘑菇帽"
STRINGS.NAMES.BLUE_MUSHROOMHAT = "蓝蘑菇帽"
STRINGS.RECIPE_DESC.RED_MUSHROOMHAT = "就像吃了各种蘑菇。"
STRINGS.RECIPE_DESC.GREEN_MUSHROOMHAT = "就像吃了各种蘑菇。"
STRINGS.RECIPE_DESC.BLUE_MUSHROOMHAT = "就像吃了各种蘑菇。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.MUSHROOMHAT = "让穿戴者看起来像个有趣的家伙。"
STRINGS.CHARACTERS.FOX.DESCRIBE.RED_MUSHROOMHAT = "红色的，真好看！"
STRINGS.CHARACTERS.FOX.DESCRIBE.GREEN_MUSHROOMHAT = "绿色的也不错~"
STRINGS.CHARACTERS.FOX.DESCRIBE.BLUE_MUSHROOMHAT = "蓝色的最漂亮！"


STRINGS.RECIPE_DESC.BLOWDART = "远程攻击的好帮手"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOWDART = "吹一下试试"
STRINGS.CHARACTERS.FOX.DESCRIBE.BLOWDART = "咻——"

STRINGS.NAMES.BLOWDART_YELLOW = "雷电吹箭"
STRINGS.RECIPE_DESC.BLOWDART_YELLOW = "电击敌人\n效果惊人。"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.BLOWDART_YELLOW = "它的准确性令人震惊。"
STRINGS.CHARACTERS.FOX.DESCRIBE.BLOWDART_YELLOW = "带电的吹箭！"

--------------------------<猴岛补充>--------------------------
STRINGS.NAMES.DUG_MONKEYTAIL = "猴尾草"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_MONKEYTAIL = "可以重新种下去"
STRINGS.CHARACTERS.FOX.DESCRIBE.DUG_MONKEYTAIL = "换个地方种"

STRINGS.NAMES.DUG_BANANABUSH = "香蕉丛"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DUG_BANANABUSH = "可以重新种下去"
STRINGS.CHARACTERS.FOX.DESCRIBE.DUG_BANANABUSH = "换个地方种"

STRINGS.NAMES.DST_CAVE_ENTRANCE = "洞穴入口"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DST_CAVE_ENTRANCE = "通往地下的入口"
STRINGS.CHARACTERS.FOX.DESCRIBE.DST_CAVE_ENTRANCE = "下去看看吧"

STRINGS.NAMES.DST_CAVE_EXIT = "洞穴出口"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DST_CAVE_EXIT = "回到地面的绳索"
STRINGS.CHARACTERS.FOX.DESCRIBE.DST_CAVE_EXIT = "上去吧"

--------------------------<远古档案馆>--------------------------
STRINGS.NAMES.ATRIUM_FENCE = "远古围栏"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ATRIUM_FENCE = "远古文明的遗迹"
STRINGS.CHARACTERS.FOX.DESCRIBE.ATRIUM_FENCE = "很古老的围栏"

STRINGS.NAMES.ATRIUM_LIGHT = "远古灯柱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ATRIUM_LIGHT = "散发着微光的远古灯柱"
STRINGS.CHARACTERS.FOX.DESCRIBE.ATRIUM_LIGHT = "还在亮着"

STRINGS.NAMES.ATRIUM_OVERGROWTH = "远古方尖碑"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ATRIUM_OVERGROWTH = "这些符号我一个都不认得。"
STRINGS.CHARACTERS.FOX.DESCRIBE.ATRIUM_OVERGROWTH = "上面刻着奇怪的文字"

STRINGS.NAMES.ATRIUM_PILLAR = "远古石柱"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ATRIUM_PILLAR = "一根古老的石柱"
STRINGS.CHARACTERS.FOX.DESCRIBE.ATRIUM_PILLAR = "好古老"

STRINGS.NAMES.ATRIUM_RUBBLE = "远古壁画"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ATRIUM_RUBBLE = "残破的远古壁画"
STRINGS.CHARACTERS.FOX.DESCRIBE.ATRIUM_RUBBLE = "画了什么在上面"

STRINGS.NAMES.FOSSIL_MOUND = "化石堆"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.FOSSIL_MOUND = "也许里面藏着什么"
STRINGS.CHARACTERS.FOX.DESCRIBE.FOSSIL_MOUND = "挖挖看"

--------------------------<启蒙系统>--------------------------
GLOBAL.ANNOUNCE_ENLIGHTENMENT_START = "月光的力量在体内涌动..."
GLOBAL.ANNOUNCE_ENLIGHTENMENT_END = "启蒙的感觉消退了"
GLOBAL.ANNOUNCE_ENLIGHTENMENT_GESTALT_SPAWN = "月灵出现了！"
GLOBAL.ANNOUNCE_ENLIGHTENMENT_HIGH = "月灵的力量越来越强..."

--------------------------<水中木>--------------------------
STRINGS.RECIPE_DESC.OCEANTREE_PILLAR = "等待完善……"

--------------------------<梦魇疯猪 Daywalker>--------------------------
STRINGS.NAMES.DAYWALKER = "梦魇疯猪"
STRINGS.NAMES.DAYWALKER_PILLAR = "囚禁柱"
STRINGS.NAMES.SHADOW_LEECH = "暗影水蛭"
STRINGS.NAMES.DREADSTONE = "恐惧石"
STRINGS.NAMES.HORRORFUEL = "恐怖燃料"
STRINGS.NAMES.ARMORDREADSTONE = "恐惧石甲"
STRINGS.NAMES.DREADSTONEHAT = "恐惧石头盔"
STRINGS.NAMES.WALL_DREADSTONE_ITEM = "恐惧石墙"
STRINGS.NAMES.SUPPORT_PILLAR_DREADSTONE_SCAFFOLD = "恐惧石支撑柱"

STRINGS.RECIPE_DESC.DREADSTONE = "来自深渊的恐惧结晶"
STRINGS.RECIPE_DESC.HORRORFUEL = "浓缩的恐怖能量"
STRINGS.RECIPE_DESC.ARMORDREADSTONE = "恐惧石打造的护甲"
STRINGS.RECIPE_DESC.DREADSTONEHAT = "恐惧石打造的头盔"
STRINGS.RECIPE_DESC.WALL_DREADSTONE_ITEM = "恐惧石打造的墙壁"

STRINGS.CHARACTERS.GENERIC.DESCRIBE.DAYWALKER = "被囚禁的古老生物..."
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DAYWALKER_PILLAR = "这些柱子囚禁着什么东西"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SHADOW_LEECH = "黏糊糊的暗影生物"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DREADSTONE = "散发着不祥的气息"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.HORRORFUEL = "摸起来让人不安"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.ARMORDREADSTONE = "穿上它让我感到沉重"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.DREADSTONEHAT = "视野边缘有红色闪烁"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.WALL_DREADSTONE_ITEM = "冰冷而坚固"
STRINGS.CHARACTERS.GENERIC.DESCRIBE.SUPPORT_PILLAR_DREADSTONE_SCAFFOLD = "支撑洞穴的柱子"