GLOBAL.setmetatable(env,{
    __index=function(t,k) return GLOBAL.rawget(GLOBAL,k) end,
    __newindex=function(t,k,v) GLOBAL.rawset(GLOBAL,k,v) rawset(t,k,v) end
})

----------------<DST-only 全局变量 fallback>----------------
TILE_SCALE = TILE_SCALE or 4
CAMERASHAKE = CAMERASHAKE or { FULL = 0, SIDE = 1, VERTICAL = 2 }
MINIMAP_DECORATION_PRIORITY = MINIMAP_DECORATION_PRIORITY or 50

-- DS 没有 TileGroupManager，提供最小兼容实现
TileGroupManager = TileGroupManager or {
    IsLandTile = function(self, tile)
        return tile ~= nil and tile ~= GROUND.IMPASSABLE
    end,
    IsTemporaryTile = function(self, tile)
        return false
    end,
}

--------------------------<tuning>--------------------------
local seg_time = 30
local total_day_time = seg_time*16

local day_segs = 10
local dusk_segs = 4
local night_segs = 2

local day_time = seg_time * day_segs
local dusk_time = seg_time * dusk_segs
local night_time = seg_time * night_segs

local multiplayer_attack_modifier = 1--0.6--0.75
local multiplayer_armor_durability_modifier = 0.7
local multiplayer_armor_absorption_modifier = 1--0.75
local wilson_attack = 34 * multiplayer_attack_modifier
local wilson_health = 150

TUNING.DEFAULT_HIT_RECOVERY = 0.75


--走得慢组建
TUNING.GROGGINESS_DECAY_RATE = .01
TUNING.GROGGINESS_WEAR_OFF_DURATION = .5
TUNING.MIN_KNOCKOUT_TIME = 10
TUNING.MIN_GROGGY_SPEED_MOD = .4
TUNING.MAX_GROGGY_SPEED_MOD = .6
----
  TUNING.ALTERGUARDIAN_PLAYERDAMAGEPERCENT = 0.75

  TUNING.ALTERGUARDIAN_PHASE1_WALK_SPEED = 5
  TUNING.ALTERGUARDIAN_PHASE1_HEALTH = 4000
  TUNING.ALTERGUARDIAN_PHASE1_ROLLDAMAGE = 166.67
  TUNING.ALTERGUARDIAN_PHASE1_AOEDAMAGE = 66.67
  TUNING.ALTERGUARDIAN_PHASE1_ATTACK_PERIOD = 7.5
  TUNING.ALTERGUARDIAN_PHASE1_AOERANGE = 4.25
  TUNING.ALTERGUARDIAN_PHASE1_ROLLCOOLDOWN = 8.5
  TUNING.ALTERGUARDIAN_PHASE1_MINROLLCOUNT = 3
  TUNING.ALTERGUARDIAN_PHASE1_SUMMONCOOLDOWN = 20
  TUNING.ALTERGUARDIAN_PHASE1_TARGET_DIST = 20
  TUNING.ALTERGUARDIAN_PHASE1_SHIELDTRIGGER = 2000
  TUNING.ALTERGUARDIAN_PHASE1_SHIELDABSORB = 0.80

  TUNING.ALTERGUARDIAN_PHASE2_WALK_SPEED = 4.5
  TUNING.ALTERGUARDIAN_PHASE2_MAXHEALTH = 20000
  TUNING.ALTERGUARDIAN_PHASE2_STARTHEALTH = 6000
  TUNING.ALTERGUARDIAN_PHASE2_DAMAGE = 133.33
  TUNING.ALTERGUARDIAN_PHASE2_ATTACK_PERIOD = 6.0
  TUNING.ALTERGUARDIAN_PHASE2_CHOP_RANGE = 4.5
  TUNING.ALTERGUARDIAN_PHASE2_SPIN_RANGE = 18
  TUNING.ALTERGUARDIAN_PHASE2_SPIN_SPEED = 7.6
  TUNING.ALTERGUARDIAN_PHASE2_SPINMIN = 3
  TUNING.ALTERGUARDIAN_PHASE2_SPINMAX = 5
  TUNING.ALTERGUARDIAN_PHASE2_SPINCD = 14.25
  TUNING.ALTERGUARDIAN_PHASE2_SPIKEDAMAGE = 50
  TUNING.ALTERGUARDIAN_PHASE2_SPIKECOOLDOWN = 18.25
  TUNING.ALTERGUARDIAN_PHASE2_SPIKE_RANGE = 10
  TUNING.ALTERGUARDIAN_PHASE2_SPIKE_LIFETIME = 30
  TUNING.ALTERGUARDIAN_PHASE2_SUMMONCOOLDOWN = 24.25
  TUNING.ALTERGUARDIAN_PHASE2_TARGET_DIST = 30

  TUNING.ALTERGUARDIAN_PHASE3_WALK_SPEED = 7.5
  TUNING.ALTERGUARDIAN_PHASE3_MAXHEALTH = 22500
  TUNING.ALTERGUARDIAN_PHASE3_STARTHEALTH = 7500
  TUNING.ALTERGUARDIAN_PHASE3_RUNAWAY_BLOCK_TIME = 1.0
  TUNING.ALTERGUARDIAN_PHASE3_GOHOMEDSQ = 144
  TUNING.ALTERGUARDIAN_PHASE3_DAMAGE = 150
  TUNING.ALTERGUARDIAN_PHASE3_LASERDAMAGE = 120
  TUNING.ALTERGUARDIAN_PHASE3_ATTACK_PERIOD = 5.0
  TUNING.ALTERGUARDIAN_PHASE3_ATTACK_RANGE = 14
  TUNING.ALTERGUARDIAN_PHASE3_STAB_RANGE = 3.5
  TUNING.ALTERGUARDIAN_PHASE3_STAB_HITRANGE = 2
  TUNING.ALTERGUARDIAN_PHASE3_TRAP_CD = 40
  TUNING.ALTERGUARDIAN_PHASE3_TRAP_LT = 20
  TUNING.ALTERGUARDIAN_PHASE3_TRAP_MINRANGE = 2.0
  TUNING.ALTERGUARDIAN_PHASE3_TRAP_MAXRANGE = 3.5
  TUNING.ALTERGUARDIAN_PHASE3_TRAP_AOERANGE = 3.0
  TUNING.ALTERGUARDIAN_PHASE3_TRAP_GROGGINESS = 1.0
  TUNING.ALTERGUARDIAN_PHASE3_TRAP_KNOCKOUTTIME = 3.0
  TUNING.ALTERGUARDIAN_PHASE3_TRAP_LANDEDDAMAGE = 50
  TUNING.ALTERGUARDIAN_PHASE3_TRAP_WORKS = 3
  TUNING.ALTERGUARDIAN_PHASE3_SUMMONCOOLDOWN = 45
  TUNING.ALTERGUARDIAN_PHASE3_SUMMONMAXLOOPS = 60
  TUNING.ALTERGUARDIAN_PHASE3_SUMMONRSQ = 400 --20 ^2
  TUNING.ALTERGUARDIAN_PHASE3_TARGET_DIST = 20

  TUNING.ALTERGUARDIAN_PROJECTILE_SPEED = 20
  TUNING.ALTERGUARDIANHAT_GESTALT_DAMAGE = 42.5

--小虚影
  TUNING.GESTALT_WALK_SPEED = 1.5

  TUNING.GESTALT_SPAWN_DIST = 14
  TUNING.GESTALT_SPAWN_DIST_VAR = 3
  TUNING.GESTALT_SPAWN_MORPH_DIST = 8

  TUNING.GESTALT_INITIAL_MORPH_TIMER = seg_time
  TUNING.GESTALT_EMERGE_MORPH_DELAY = seg_time / 3

  TUNING.GESTALT_MIN_SANITY_TO_SPAWN = 0.25
  TUNING.GESTALT_POPULATION_DIST = 30
  TUNING.GESTALT_RELOCATED_FAR_DIST = 18

  TUNING.GESTALT_COMBAT_TRANSPERENCY = 0.85

  TUNING.GESTALT_AGGRESSIVE_RANGE = 6
  TUNING.GESTALT_ATTACK_RANGE = 2.5
  TUNING.GESTALT_ATTACK_HIT_RANGE_SQ = 1.5
  TUNING.GESTALT_ATTACK_COOLDOWN = 4
  TUNING.GESTALT_ATTACK_DAMAGE_SANITY = 10
  TUNING.GESTALT_ATTACK_DAMAGE_GROGGINESS = 2
  TUNING.GESTALT_ATTACK_DAMAGE_KO_TIME = 6

  TUNING.GESTALT_POPULATION_LEVEL =
{
    {
        MAX_SPAWNS = 2,
        MAX_SANITY = 0.5,
    },
    {
        MAX_SPAWNS = 3,
        MAX_SANITY = 0.8,
    },
    {
        MAX_SPAWNS = 4,
        MAX_SANITY = math.huge,
    },
}

  TUNING.GESTALT_POP_CHANGE_INTERVAL = 10
  TUNING.GESTALT_POP_CHANGE_VARIANCE = 2

  --UNUSED
  TUNING.GESTALT =
  {
   WALK_SPEED = 1.5,

   SPAWN_DIST = 14,
   SPAWN_DIST_VAR = 3,
   SPAWN_MORPH_DIST = 8,

   INITIAL_MORPH_TIMER = seg_time,
   EMERGE_MORPH_DELAY = seg_time / 3,

   MIN_SANITY_TO_SPAWN = .25,
   POPULATION_DIST = 30,
   RELOCATED_FAR_DIST = 18,

   COMBAT_TRANSPERENCY = 0.85,

   AGGRESSIVE_RANGE = 6,
   ATTACK_RANGE = 2.5,
   ATTACK_HIT_RANGE_SQ = 1.5,
   ATTACK_COOLDOWN = 4,
   ATTACK_DAMAGE_SANITY = 10,
   ATTACK_DAMAGE_GROGGINESS = 2,
   ATTACK_DAMAGE_KO_TIME = 6,

   POPULATION_LEVEL =
   {
    {
     MAX_SPAWNS = 2,
     MAX_SANITY = 0.5,
    },
    {
     MAX_SPAWNS = 3,
     MAX_SANITY = 0.8,
    },
    {
     MAX_SPAWNS = 4,
     MAX_SANITY = math.huge,
    },
   },
  }
  --大虚影
  TUNING.GESTALTGUARD_WALK_SPEED = 4
  TUNING.GESTALTGUARD_HEALTH = 200
  TUNING.GESTALTGUARD_DAMAGE = 180
  TUNING.GESTALTGUARD_ATTACK_RANGE = 3.5
  TUNING.GESTALTGUARD_WATCHING_RANGE = 6
  TUNING.GESTALTGUARD_AGGRESSIVE_RANGE = 18
  TUNING.GESTALTGUARD_MAX_DISTSQ_FROM_SPAWN_PT = 36*36

--启蒙系统 (Enlightenment)
  -- 启蒙值 = 理智值本身，不需要独立数值
  TUNING.ENLIGHTENMENT_SANITY_REGEN = 4/60       -- 启蒙状态下每秒回san量
  TUNING.ENLIGHTENMENT_TILE_SCAN_RADIUS = 20      -- 地皮密度扫描半径
  TUNING.ENLIGHTENMENT_TILE_THRESHOLD = 0.6       -- 月亮地皮占比阈值
  TUNING.ENLIGHTENMENT_LINGER_TIME = 5            -- 脱离条件后延续秒数
  TUNING.ENLIGHTENMENT_FOOD_DURATION = 30         -- 食用月亮食物启蒙持续时间(秒)
  TUNING.ENLIGHTENMENT_COMBAT_DURATION = 10       -- 被月亮敌人攻击后启蒙持续时间(秒)
  -- 阈值（百分比）
  TUNING.ENLIGHTENMENT_THRESH_GLOW = 0.25         -- 画面轻微发光
  TUNING.ENLIGHTENMENT_THRESH_SOUND = 0.40        -- 月亮环境音效
  TUNING.ENLIGHTENMENT_THRESH_SPAWN = 0.60        -- 生成月灵(behaviour 1)
  TUNING.ENLIGHTENMENT_THRESH_LEVEL2 = 0.80       -- 月灵升级(behaviour 2)
  TUNING.ENLIGHTENMENT_THRESH_LEVEL3 = 0.90       -- 月灵攻击(behaviour 3)
  -- 月灵数量上限
  TUNING.ENLIGHTENMENT_MAX_GESTALTS = 3
  -- 移速惩罚
  TUNING.ENLIGHTENMENT_SPEED_PENALTY_L2 = 0.10    -- behaviour 2 移速下降10%
  TUNING.ENLIGHTENMENT_SPEED_PENALTY_L3 = 0.20    -- behaviour 3 移速下降20%

--荧光果植物
TUNING.WORMLIGHT_PLANT_REGROW_TIME = total_day_time * 4

--蚁狮
TUNING.ANTLION_RAGE_TIME_INITIAL = 4.2 * 480
TUNING.ANTLION_RAGE_TIME_MIN = 1 * 480
TUNING.ANTLION_RAGE_TIME_MAX = 6 * 480
TUNING.ANTLION_RAGE_TIME_FAILURE_SCALE = 0.8
TUNING.ANTLION_TRIBUTE_TO_RAGE_TIME = .33 * 480
TUNING.ANTLION_RAGE_TIME_UNHAPPY_PERCENT = 0.6
TUNING.ANTLION_RAGE_TIME_HAPPY_PERCENT = 0.95
TUNING.ANTLION_TRIBUTER_TALKER_TIME = 8
TUNING.ANTLION_HEALTH = 6000
TUNING.ANTLION_MAX_ATTACK_PERIOD = 4
TUNING.ANTLION_MIN_ATTACK_PERIOD = 2
TUNING.ANTLION_SPEED_UP = -.2
TUNING.ANTLION_SLOW_DOWN = .4
TUNING.ANTLION_CAST_RANGE = 15
TUNING.ANTLION_CAST_MAX_RANGE = 20
TUNING.ANTLION_WALL_CD = 20
TUNING.ANTLION_HIT_RECOVERY = 1
TUNING.ANTLION_EAT_HEALING = 200
--蚁狮地震
TUNING.ANTLION_SINKHOLE_WORKTOREPAIR = 3
TUNING.ANTLION_SINKHOLE =
{
    RADIUS = 2.5,
    UNEVENGROUND_RADIUS = 3,

    WAVE_MAX_ATTACKS = 5,
    WAVE_MIN_ATTACKS = 2,
    WAVE_ATTACK_DELAY = .75,
    WAVE_ATTACK_DELAY_VARIANCE = 1,
    WAVE_MERGE_ATTACKS_DIST_SQ = math.pow(4 * 3, 2), -- 4 == TILE_SCALE

    NUM_WARNINGS = 12,
    WARNING_DELAY = 1,
    WARNING_DELAY_VARIANCE = .3,

    ATTACK_SEQUENCE_INITIAL_DELAY = 1 * 480,
    ATTACK_SEQUENCE_INITIAL_DELAY_VARIANCE = 1 * 480,
    ATTACK_SEQUENCE_NEXT_WAVE_DELAY = .35 * 480, -- useage: val * remaing days in season
    ATTACK_SEQUENCE_NEXT_WAVE_DELAY_VARIANCE = 1 * 480,

    DAMAGE = 30,
    
    REPAIR_TIME_VARIANCE = 1 * 480,
    REPAIR_TIME = -- Note: these times are used from last to first
    {
    4 * 480,
    5 * 480,
    21 * 480,
    },
        }

        TUNING.SANDSPIKE =
        {
    HEALTH =
    {
        SHORT = 25,
        MED = 65,
        TALL = 100,
        BLOCK = 250,
    },
    DAMAGE =
    {
        SHORT = 100,
        MED = 150,
        TALL = 200,
        BLOCK = 0,
    },
    LIFETIME =
    {
        SHORT = { 6, 7 },
        MED = { 7, 8 },
        TALL = { 8, 10 },
        BLOCK = { 15, 16 },
    },
}

--邪天翁
 TUNING.MALBATROSS_HEALTH = 2500 * 2
 TUNING.MALBATROSS_DAMAGE = 150
 
 TUNING.MALBATROSS_DAMAGE_PLAYER_PERCENT = .5
 TUNING.MALBATROSS_ATTACK_PERIOD = 4
 TUNING.MALBATROSS_ATTACK_RANGE = 5
 TUNING.MALBATROSS_AOE_RANGE = 3 +1 --增加点难度
 TUNING.MALBATROSS_AOE_SCALE = 0.8
 TUNING.MALBATROSS_LOSE_TARGET_PERIOD = 60
 TUNING.MALBATROSS_BOAT_DAMAGE = 5
 TUNING.MALBATROSS_BOAT_PUSH = 2
 TUNING.MALBATROSS_NOTHUNGRY_TIME =
 {
     MIN = 15,
     MAX = 25,
 }
 TUNING.MALBATROSS_MISSFISH_TIME =
 {
     MIN = 10,
     MAX = 10,
 }
 
 TUNING.MALBATROSS_ENTITYSLEEP_RELOCATE_TIME = 3 * 480 --total_day_time,
 TUNING.MALBATROSS_EATSUCCESS_CHANCE = 0.50
 TUNING.MALBATROSS_MAX_CHASEAWAY_DIST = 50
 TUNING.MALBATROSS_NOTICEPLAYER_DISTSQ = 400 -- 20 * 20
 TUNING.MALBATROSS_STOLENFISH_AGGROCOUNT = 2
 TUNING.MALBATROSS_HOOKEDFISH_SUMMONCHANCE = 0.1

 TUNING.EXPLOSIVE_MAX_RESIST_DAMAGE = 8000
 TUNING.EXPLOSIVE_RESIST_DECAY_TIME = 8
 TUNING.EXPLOSIVE_RESIST_DECAY_DELAY = 2

--邪天翁
 TUNING.MALBATROSS_HEALTH = 2500 * 2
 TUNING.MALBATROSS_DAMAGE = 150
 
 TUNING.MALBATROSS_DAMAGE_PLAYER_PERCENT = .5
 TUNING.MALBATROSS_ATTACK_PERIOD = 4
 TUNING.MALBATROSS_ATTACK_RANGE = 5
 TUNING.MALBATROSS_AOE_RANGE = 3 +1 --增加点难度
 TUNING.MALBATROSS_AOE_SCALE = 0.8
 TUNING.MALBATROSS_LOSE_TARGET_PERIOD = 60
 TUNING.MALBATROSS_BOAT_DAMAGE = 5
 TUNING.MALBATROSS_BOAT_PUSH = 2
 TUNING.MALBATROSS_NOTHUNGRY_TIME =
 {
     MIN = 15,
     MAX = 25,
 }
 TUNING.MALBATROSS_MISSFISH_TIME =
 {
     MIN = 10,
     MAX = 10,
 }
 
 TUNING.MALBATROSS_ENTITYSLEEP_RELOCATE_TIME = 3 * 480 --total_day_time,
 TUNING.MALBATROSS_EATSUCCESS_CHANCE = 0.50
 TUNING.MALBATROSS_MAX_CHASEAWAY_DIST = 50
 TUNING.MALBATROSS_NOTICEPLAYER_DISTSQ = 400 -- 20 * 20
 TUNING.MALBATROSS_STOLENFISH_AGGROCOUNT = 2
 TUNING.MALBATROSS_HOOKEDFISH_SUMMONCHANCE = 0.1

 TUNING.EXPLOSIVE_MAX_RESIST_DAMAGE = 8000
 TUNING.EXPLOSIVE_RESIST_DECAY_TIME = 8
 TUNING.EXPLOSIVE_RESIST_DECAY_DELAY = 2
 
--月台
TUNING.SCULPTURE_COMPLETE_WORK = 10
TUNING.SCULPTURE_COVERED_WORK = 6

TUNING.GARGOYLE_MINE = 4
TUNING.GARGOYLE_MINE_LOW = 2
TUNING.GARGOYLE_REANIMATE_DELAY = .2--6 * FRAMES--FRAMES is not declared at worldgen YO

TUNING.MOONBASE_CHARGE_DELAY = 10 --so it won't start right away as it fades to night
TUNING.MOONBASE_CHARGE_DURATION = seg_time * 2 - 10.1 --tiny error to make sure it fits within a 2 seg night
TUNING.MOONBASE_CHARGE_DURATION1 = 18.7 --18.6, --first stage, to match music length
TUNING.MOONBASE_COMPLETE_WORK = 6
TUNING.MOONBASE_DAMAGED_WORK = 4

TUNING.MOONHOUND_HEALTH = 150
TUNING.MOONHOUND_DAMAGE = 20
TUNING.MOONHOUND_ATTACK_PERIOD = 2
TUNING.MOONHOUND_SPEED = 10
TUNING.MOONHOUND_AGGRO_DIST = 15
TUNING.MOONHOUND_RETURN_DIST = 30
TUNING.MOONHOUND_FREEZE_WEAR_OFF_TIME = 3

TUNING.MOONPIG_AGGRO_DIST = 15
TUNING.MOONPIG_RETURN_DIST = 30
TUNING.MOONPIG_FREEZE_WEAR_OFF_TIME = 3

TUNING.YELLOWSTAFF_STAR_DURATION = total_day_time * 3.5
TUNING.OPALSTAFF_STAR_DURATION = total_day_time * 2
TUNING.MUTATEDHOUND_SPAWN_CHANCE = 0.5

--联机龙蝇
TUNING.DRAGONFLY2_SPAWN_TIME = 1
TUNING.DRAGONFLY2_RESPAWN_TIME = total_day_time*20

TUNING.DRAGONFLY2_HEALTH = 27500
TUNING.DRAGONFLY2_DAMAGE = 150
TUNING.DRAGONFLY2_ATTACK_PERIOD = 4
TUNING.DRAGONFLY2_ATTACK_RANGE = 4
TUNING.DRAGONFLY2_HIT_RANGE = 5
TUNING.DRAGONFLY2_SPEED = 5

TUNING.DRAGONFLY2_FIRE_ATTACK_PERIOD = 3
TUNING.DRAGONFLY2_FIRE_DAMAGE = 300
TUNING.DRAGONFLY2_FIRE_HIT_RANGE = 6
TUNING.DRAGONFLY2_FIRE_SPEED = 7

TUNING.DRAGONFLY2_RESET_DIST = 60
TUNING.DRAGONFLY2_AGGRO_DIST = 15

TUNING.DRAGONFLY2_STUN = 625 --1250 --掉龙蝇皮所需伤害
TUNING.DRAGONFLY2_STUN_PERIOD = 5
TUNING.DRAGONFLY2_STUN_DURATION = 10
TUNING.DRAGONFLY2_STUN_COOLDOWN = 60
TUNING.DRAGONFLY2_STUN_RESIST = 250

TUNING.DRAGONFLY2_ENRAGE_DURATION = 60
TUNING.DRAGONFLY2_BREAKOFF_DAMAGE = 2500

TUNING.DRAGONFLY2_FREEZE_RESIST = 100
TUNING.DRAGONFLY2_POUND_CD = 20
TUNING.DRAGONFLY2_HIT_RECOVERY = 2
TUNING.DRAGONFLY2_FLYING_HIT_RECOVERY = 4

TUNING.DRAGONFLY2_FREEZE_THRESHOLD = 8
TUNING.DRAGONFLY2_ENRAGED_FREEZE_THRESHOLD = 12

TUNING.LAVAE_HEALTH = 500
TUNING.LAVAE_DAMAGE = 50
TUNING.LAVAE_ATTACK_PERIOD = 4
TUNING.LAVAE_HIT_RANGE = 3
TUNING.LAVAE_ATTACK_RANGE = 6
TUNING.LAVAE_HUNGER_RATE = 50/total_day_time
TUNING.LAVAE_LIFESPAN = 30

TUNING.LAVAE_HATCH_CRACK_TIME = 10
TUNING.LAVAE_HATCH_TIME = total_day_time*2
TUNING.LAVAE_HATCH_FAIL_TIME = night_time

--克劳斯
 TUNING.DEER_DAMAGE = 25
 TUNING.DEER_HEALTH = 350 * 2 -- harder for multiplayer
 TUNING.DEER_ATTACK_RANGE = 3
 TUNING.DEER_ATTACK_PERIOD = 2
 TUNING.DEER_ATTACKER_REMEMBER_DIST = 20
 TUNING.DEER_WALK_SPEED = 2.5
 TUNING.DEER_RUN_SPEED = 8

 TUNING.DEER_HERD_MOVE_DIST = 10

 TUNING.DEER_GEMMED_DAMAGE = 50
 TUNING.DEER_GEMMED_HEALTH = 1500
 TUNING.DEER_GEMMED_AGGRO_DIST = 10
 TUNING.DEER_GEMMED_FIRST_CAST_CD = 4
 TUNING.DEER_GEMMED_CAST_RANGE = 12
 TUNING.DEER_GEMMED_CAST_MAX_RANGE = 15
 TUNING.DEER_GEMMED_MAX_SPELLS = 6

 TUNING.DEER_ICE_BURN_PANIC_TIME = 10
 TUNING.DEER_ICE_SPEED_PENALTY = .4
 TUNING.DEER_ICE_TEMPERATURE = -2
 TUNING.DEER_ICE_FATIGUE = .1
 TUNING.DEER_ICE_FREEZE_LOCK_FRAMES = 30
 TUNING.DEER_ICE_CAST_CD = 10

 TUNING.DEER_FIRE_FREEZE_WEAR_OFF_TIME = 5
 TUNING.DEER_FIRE_TEMPERATURE = 72 --must be higher than OVERHEAT_TEMP
 TUNING.DEER_FIRE_IGNITE_FRAMES = 30
 TUNING.DEER_FIRE_CAST_CD = 8

 TUNING.KLAUS_HEALTH = 10000
 TUNING.KLAUS_HEALTH_REGEN = 25 --per second (only when not in combat)
 TUNING.KLAUS_HEALTH_REZ = .5
 TUNING.KLAUS_DAMAGE = 75
 TUNING.KLAUS_ATTACK_PERIOD = 3
 TUNING.KLAUS_ATTACK_RANGE = 3
 TUNING.KLAUS_HIT_RANGE = 4
 TUNING.KLAUS_SPEED = 2.75
 TUNING.KLAUS_HIT_RECOVERY = 1

 TUNING.KLAUS_ENRAGE_SCALE = 1.4

 TUNING.KLAUS_NAUGHTY_MIN_SPAWNS = 2
 TUNING.KLAUS_NAUGHTY_MAX_SPAWNS = 6

 TUNING.KLAUS_COMMAND_CD = 6

 TUNING.KLAUS_CHOMP_CD = 6
 TUNING.KLAUS_CHOMP_MIN_RANGE = 4.5
 TUNING.KLAUS_CHOMP_RANGE = 7
 TUNING.KLAUS_CHOMP_MAX_RANGE = 9 --for scaling
 TUNING.KLAUS_CHOMP_HIT_RANGE = 3.5

 TUNING.KLAUS_AGGRO_DIST = 15
 TUNING.KLAUS_DEAGGRO_DIST = 30
 TUNING.KLAUS_EPICSCARE_RANGE = 10

 TUNING.KLAUSSACK_EVENT_RESPAWN_TIME = total_day_time * 20 -- winters feast event respawn time
 TUNING.KLAUSSACK_RESPAWN_DELAY = total_day_time * 10
 TUNING.KLAUSSACK_SPAWN_DELAY = total_day_time * 1
 TUNING.KLAUSSACK_SPAWN_DELAY_VARIANCE = total_day_time * 2
 TUNING.KLAUSSACK_MAX_SPAWNS = 1
 TUNING.SPAWN_KLAUS = true

--暗影三基佬
TUNING.SHADOW_CHESSPIECE_EPICSCARE_RANGE = 10
TUNING.SHADOW_CHESSPIECE_DESPAWN_TIME = 30

TUNING.SHADOW_ROOK =
        {
            LEVELUP_SCALE = {1, 1.2, 1.6},
            SPEED = 7,                          -- levels are procedural
            HEALTH = {1000, 4000, 10000},
            DAMAGE = {45, 100, 165},
            ATTACK_PERIOD = {6, 5.5, 5},
            ATTACK_RANGE = 8,                   -- levels are procedural
            HIT_RANGE = 3.35,
            RETARGET_DIST = 15,
        }

TUNING.SHADOW_KNIGHT =
        {
            LEVELUP_SCALE = {1, 1.7, 2.5},
            SPEED = {7, 9, 12},
            HEALTH = {900, 2700, 8100},
            DAMAGE = {40, 90, 150},
            ATTACK_PERIOD = {3, 2.5, 2},
            ATTACK_RANGE = 2.3,                 -- levels are procedural
            ATTACK_RANGE_LONG = 4.5,            -- levels are procedural
            RETARGET_DIST = 15,
        }

TUNING.SHADOW_BISHOP =
        {
            LEVELUP_SCALE = {1, 1.6, 2.2},
            SPEED = 3,                          -- levels are procedural
            HEALTH = {800, 2500, 7500},
            DAMAGE = {20, 35, 60},
            ATTACK_PERIOD = {15, 14, 12},
            ATTACK_RANGE = {4, 6, 8},           -- levels are procedural
            HIT_RANGE = 1.75,
            ATTACK_TICK = .5,
            ATTACK_START_TICK = .2,
            RETARGET_DIST = 15,
        }

TUNING.SCULPTURE_COMPLETE_WORK = 10
TUNING.SCULPTURE_COVERED_WORK = 6

--温泉
TUNING.HOTSPRING_GEM_DROP_CHANCE = 0.2
TUNING.HOTSPRING_GLOW =
{
    RADIUS = 2.00,
    INTENSITY = 0.75,
    FALLOFF = 0.75,
}
TUNING.HOTSPRING_WORK = 6
TUNING.HOTSPRING_IDLE =
{
    BASE = 3,
    DELAY = 4,
}
TUNING.HOTSPRING_HEAT =
{
    ACTIVE = 90,
    PASSIVE = 45,
}

--水中木
TUNING.WATERTREE_PILLAR_CANOPY_BUFFER = 1
TUNING.WATERTREE_PILLAR_RAM_RECHARGE_TIME = 1.5
TUNING.MAX_WALKABLE_PLATFORM_RADIUS = 4
TUNING.OCEANTREE_PILLAR_CHOPS = 25
TUNING.SHADE_CANOPY_RANGE_SMALL = 22

TUNING.OCEANVINE_REGROW_TIME = total_day_time*2.5
TUNING.OCEANVINE_COCOON_SPIDER_RADIUS = 16

--沙漠绿洲
TUNING.OASISLAKE_MAX_FISH = 15
TUNING.OASISLAKE_FISH_RESPAWN_TIME = seg_time * 3

--月树
TUNING.TREE_BURN_TIME = 45
TUNING.MOON_TREE_REGROWTH = {
            OFFSPRING_TIME = total_day_time * 3,
            DESOLATION_RESPAWN_TIME = total_day_time * 50,
            DEAD_DECAY_TIME = total_day_time * 30,
        }

TUNING.MOON_TREE_GROWTH_TIME =
        {
            {base=1.5*day_time, random=0.5*day_time},   --short
            {base=5*day_time, random=2*day_time},       --normal
            {base=5*day_time, random=2*day_time},       --tall
        }

--月蘑菇
TUNING.MUSHTREE_REGROWTH = {
    OFFSPRING_TIME = total_day_time * 3,
    DESOLATION_RESPAWN_TIME = total_day_time * 50,
    DEAD_DECAY_TIME = total_day_time * 30,
}

TUNING.MOONMUSHTREE_REGROWTH_TIME_MULT = TUNING.MOONMUSHTREE_REGROWTH_TIME_MULT or 1
TUNING.REGROWTH_TIME_MULTIPLIER = TUNING.REGROWTH_TIME_MULTIPLIER or 1

TUNING.MOON_TREE_CHOPS_SMALL = 8
TUNING.MOON_TREE_CHOPS_NORMAL = 12
TUNING.MOON_TREE_CHOPS_TALL = 16  -- 4 chops per log
TUNING.MOON_TREE_DEPLOY_SPACING = 4	--DO NOT USE! (use DEPLOYSPACING enums instead)
										--NOTE: went with PLACER_DEFAULT (matches enum 4), but size 3.2
										--      instead of LARGE (enum 5), which matches size 4
										--      This results in no change in behaviour.

TUNING.PALMCONETREE_CHOPS_SMALL = 5
TUNING.PALMCONETREE_CHOPS_NORMAL = 10
TUNING.PALMCONETREE_CHOPS_TALL = 15
--月娥
TUNING.MOONBUTTERFLY_SPEED = 2.5
TUNING.MOONBUTTERFLY_PERISH_TIME = total_day_time / 2
TUNING.MOONBUTTERFLY_PERISH_INV_MODIFIER = 0.25

--温泉
TUNING.HOTSPRING_GEM_DROP_CHANCE = 0.2
TUNING.HOTSPRING_GLOW =
{
    RADIUS = 2.00,
    INTENSITY = 0.75,
    FALLOFF = 0.75,
}
TUNING.HOTSPRING_WORK = 6
TUNING.HOTSPRING_IDLE =
{
    BASE = 3,
    DELAY = 4,
}
TUNING.HOTSPRING_HEAT =
{
    ACTIVE = 90,
    PASSIVE = 45,
}

--石果
TUNING.ROCK_FRUIT_MINES = 1
TUNING.ROCK_FRUIT_LOOT =
        {
            ANGLE = 65,
            SPEED = -1.8,
            HEIGHT = 0.5,
            RIPE_CHANCE = 0.65,
            SEED_CHANCE = 0.01,
            MAX_SPAWNS = 10, -- NOTES(JBK): Deprecated, kept around for mods.
        }
TUNING.ROCK_FRUIT_SPROUT_GROWTIME = 5*day_time
TUNING.ROCK_FRUIT_REGROW =
        {
            EMPTY = { BASE = 2*day_time, VAR = 2*seg_time },
            PREPICK = { BASE = 6*seg_time, VAR = 2*seg_time },
            PICK = { BASE = 3*day_time, VAR = 2*seg_time },
            CRUMBLE = { BASE = 1*day_time, VAR = 2*seg_time },
        }

TUNING.ROCK_FRUIT_PICKABLE_CYCLES = 3

--月岛那三个雕像
TUNING.MOON_ALTAR_COMPLETE_WORK = 3
TUNING.MOON_ALTAR_ASTRAL_COMPLETE_WORK = 2
TUNING.MOON_ALTAR_ESTABLISH_LINK_RADIUS = 20
TUNING.MOON_ALTAR_LINK_MAX_ABS_DOT = 0.975

TUNING.MOONALTAR_ROCKS_MINE = 20

TUNING.MOON_ALTAR_LINK_AREA_CLEAR_RADIUS = 6
TUNING.MOON_ALTAR_LINK_POINT_VALID_RADIUS_SQ = 2.5*2.5
TUNING.MOON_ALTAR_LINK_ALTAR_MIN_RADIUS_SQ = 2.5*2.5

-- PROTOTYPER_TREES 常量：供 moon_altar/moonrockseed prefab 设置 prototyper.trees
TUNING.PROTOTYPER_TREES = TUNING.PROTOTYPER_TREES or {}
TUNING.PROTOTYPER_TREES.MOON_ALTAR = { CELESTIAL = 1 }       -- 未链接祭坛（stage 2 普通 / moonrockseed 基础）
TUNING.PROTOTYPER_TREES.MOON_ALTAR_FULL = { CELESTIAL = 4 }  -- 完整祭坛（stage 3 / 链接后 / moon_altar_cosmic）

TUNING.METEOR_SMASH_INVITEM_CHANCE = 0.75

--破碎蜘蛛
TUNING.SPIDER_HIDER_WALK_SPEED = 3
TUNING.SPIDER_HIDER_RUN_SPEED = 5
TUNING.SPIDER_MOON_HEALTH = 250
TUNING.SPIDER_MOON_DAMAGE = 25
TUNING.SPIDER_MOON_SPIKE_DAMAGE = 10
TUNING.SPIDER_MOON_ATTACK_PERIOD = 3

        TUNING.MOONSPIDERDEN_WORK = 8
        TUNING.MOONSPIDERDEN_CREEPRADIUS = { 8, 12, 14 }
        TUNING.MOONSPIDERDEN_WORK_REGENTIME = 4*seg_time
        TUNING.MOONSPIDERDEN_SPIDERS = {2, 3, 4}
        TUNING.MOONSPIDERDEN_SPIDER_REGENTIME = 4*seg_time
        TUNING.MOONSPIDERDEN_RELEASE_TIME = 3*seg_time
        TUNING.MOONSPIDERDEN_EMERGENCY_WARRIORS = {0, 0, 0}
        TUNING.MOONSPIDERDEN_EMERGENCY_RADIUS = {10, 15, 20}
        TUNING.MOONSPIDERDEN_MAX_INVESTIGATORS = {1, 2, 2}
        TUNING.MOONSPIDERDEN_ENABLED = true

        --UNUSED
        TUNING.MOONSPIDERDEN =
        {
            WORK = 8,
            CREEPRADIUS = { 8, 12, 14 },
            WORK_REGENTIME = 4*seg_time,
            SPIDERS = {2, 3, 4},
            SPIDER_REGENTIME = 4*seg_time,
            RELEASE_TIME = 3*seg_time,
            EMERGENCY_WARRIORS = {0, 0, 0},
            EMERGENCY_RADIUS = {10, 15, 20},
            MAX_INVESTIGATORS = {1, 2, 2},
        }

--暗影织影者
TUNING.STALKER_HEALTH = 4000
TUNING.STALKER_DAMAGE = 200
TUNING.STALKER_ATTACK_PERIOD = 4
TUNING.STALKER_ATTACK_RANGE = 2.4
TUNING.STALKER_HIT_RANGE = 3.8
TUNING.STALKER_AOE_RANGE = 2
TUNING.STALKER_AOE_SCALE = .8
TUNING.STALKER_SPEED = 4.2
TUNING.STALKER_HIT_RECOVERY = 1.5

TUNING.STALKER_ABILITY_RETRY_CD = 3

TUNING.STALKER_SNARE_RANGE = 12
TUNING.STALKER_SNARE_MAX_RANGE = 15
TUNING.STALKER_SNARE_TIME = 6
TUNING.STALKER_SNARE_TIME_VARIANCE = .5
TUNING.STALKER_MAX_SNARES = 6
TUNING.STALKER_SNARE_CD = 10
TUNING.STALKER_FIRST_SNARE_CD = 5

TUNING.STALKER_AGGRO_DIST = 15
TUNING.STALKER_KEEP_AGGRO_DIST = 9
TUNING.STALKER_DEAGGRO_DIST = 30
TUNING.STALKER_EPICSCARE_RANGE = 10

TUNING.STALKER_BLOOM_DECAY = 5

TUNING.STALKER_ATRIUM_HEALTH = 16000
TUNING.STALKER_ATRIUM_PHASE2_HEALTH = 10000
TUNING.STALKER_ATRIUM_ATTACK_PERIOD = 3

TUNING.FOSSIL_SPIKE_DAMAGE = 100
TUNING.STALKER_SPIKES_CD = 8
TUNING.STALKER_FIRST_SPIKES_CD = 4

TUNING.STALKER_CHANNELERS_COUNT = 6
TUNING.STALKER_CHANNELERS_CD = 20
TUNING.STALKER_FIRST_CHANNELERS_CD = 5

TUNING.STALKER_FEAST_HEALING = 400
TUNING.STALKER_MINIONS_LIFESPAN = 45
TUNING.STALKER_MINIONS_LIFESPAN_VARIANCE = 5
TUNING.STALKER_MINIONS_COUNT = 20
TUNING.STALKER_MINIONS_CD = 20
TUNING.STALKER_FIRST_MINIONS_CD = 5

TUNING.STALKER_MINDCONTROL_RANGE = 15
TUNING.STALKER_MINDCONTROL_DURATION = 3.5
TUNING.STALKER_MINDCONTROL_CD = 15
TUNING.STALKER_FIRST_MINDCONTROL_CD = 5

TUNING.THURIBLE_FUEL_MAX = (night_time + dusk_time) * 3
TUNING.THURIBLE_AOE_RANGE = 6

TUNING.ATRIUM_GATE_DESTABILIZE_DELAY = 12
TUNING.ATRIUM_GATE_DESTABILIZE_TIME = seg_time * 8
TUNING.ATRIUM_GATE_DESTABILIZE_WARNING_TIME = seg_time * 0.55
TUNING.ATRIUM_GATE_DESTABILIZE_INITIAL_WARNING_DELAY = 2 -- this is the time after ATRIUM_GATE_DESTABILIZE_DELAY that the first pulse will happen
TUNING.ATRIUM_GATE_COOLDOWN = total_day_time * 20

TUNING.REVIVE_SHADOW_SANITY_PENALTY = -40

----------------<猴岛 Monkey Island TUNING>----------------
local seg_time_m = TUNING.TOTAL_DAY_TIME / 16 or 20
local total_day_time_m = TUNING.TOTAL_DAY_TIME or 320

-- 猴子基础
TUNING.MONKEY_MELEE_DAMAGE = 20
TUNING.MONKEY_HEALTH = 125
TUNING.MONKEY_ATTACK_PERIOD = 2
TUNING.MONKEY_MELEE_RANGE = 3
TUNING.MONKEY_RANGED_DAMAGE = 0
TUNING.MONKEY_RANGED_RANGE = 17
TUNING.MONKEY_MOVE_SPEED = 7
TUNING.MONKEY_NIGHTMARE_CHASE_DIST = 40
TUNING.MONKEY_FOLLOW_PLAYER_CHANCE = 0.15
TUNING.MONKEY_FOLLOW_PLAYER_WITH_BANANA_CHANCE = 0.6

-- 火药猴
TUNING.POWDER_MONKEY_HEALTH = 200
TUNING.POWDER_MONKEY_DAMAGE = 20

-- 猴子桶
TUNING.MONKEYBARREL_REGEN_PERIOD = seg_time_m * 4
TUNING.MONKEYBARREL_SPAWN_PERIOD = seg_time_m
TUNING.MONKEYBARREL_CHILDREN = {min = 3, max = 4}
TUNING.MONKEYBARREL_ENABLED = true

-- 猴子窝
TUNING.MONKEYHUT_WORKS = 4
TUNING.MONKEYHUT_REGEN_TIME = total_day_time_m * 3
TUNING.MONKEYHUT_RELEASE_TIME = 10
TUNING.MONKEYHUT_MONKEYS = 1
TUNING.MONKEYHUT_EMERGENCY_MONKEYS = 1
TUNING.MONKEYHUT_EMERGENCY_RADIUS = 10
TUNING.MONKEYHUT_ENABLED = true

-- 香蕉丛 / 猴子尾巴收获次数
TUNING.BANANABUSH_CYCLES = 4
TUNING.BANANABUSH_CYCLES_VAR = 3
TUNING.MONKEYTAIL_CYCLES = 4
TUNING.MONKEYTAIL_CYCLES_VAR = 3

-- 洞穴香蕉
TUNING.CAVE_BANANA_GROW_TIME = 4 * total_day_time_m
TUNING.CAVE_BANANA_TREE_REGROWTH_TIME = total_day_time_m * 5
TUNING.CAVE_BANANA_TREE_REGROWTH_TIME_MULT = 1

-- 海盗短剑
TUNING.CUTLESS_DAMAGE = 27
TUNING.CUTLESS_USES = 75

----------------<月蘑菇森林 Moon Mushroom Forest TUNING>----------------
-- 孢子吹箭颜色常量（DST移植）
TUNING.YELLOW_DART_DAMAGE = TUNING.YELLOW_DART_DAMAGE or 100
TUNING.YELLOW_DART_DAMAGE_DS = TUNING.YELLOW_DART_DAMAGE_DS or 100

-- 蘑菇地精
TUNING.MUSHGNOME_HEALTH = 600
TUNING.MUSHGNOME_SPORESPAWN_MIN = 2
TUNING.MUSHGNOME_SPORESPAWN_MAX = 4
TUNING.MUSHGNOME_ATTACK_PERIOD = 8
TUNING.MUSHGNOME_SPAWN_RADIUSSQ = 400
TUNING.MUSHGNOME_RELEASE_TIME = 20
TUNING.MUSHGNOME_REGEN_TIME = total_day_time
TUNING.MUSHGNOME_MAX_CHILDREN = 1
TUNING.MUSHGNOME_ENABLED = true

-- 月蘑菇孢子密度
TUNING.MUSHSPORE_MAX_DENSITY = 10
TUNING.MUSHSPORE_MAX_DENSITY_RAD = 20

-- 无眼蝠（月蘑菇光源生成器用）
TUNING.MOLEBAT_TARGET_DIST = 5
TUNING.MOLEBAT_WALK_SPEED = 5
TUNING.MOLEBAT_ATTACK_PERIOD = 2
TUNING.MOLEBAT_ATTACK_RANGE = 2
TUNING.MOLEBAT_HEALTH = 150
TUNING.MOLEBAT_DAMAGE = 30
TUNING.MOLEBAT_MAX_CHASE_DSQ = 225
TUNING.MOLEBAT_NAP_COOLDOWN = seg_time * 9
TUNING.MOLEBAT_NAP_LENGTH = seg_time * 4
TUNING.MOLEBAT_ALLY_COOLDOWN = total_day_time * 2
TUNING.MOLEBAT_ENABLED = true

-- 档案馆水池
TUNING.GROTTO_POOL_BIG_RADIUS = 5.5
TUNING.GROTTO_POOL_SMALL_RADIUS = 2.0
TUNING.GROTTO_MOONGLASS_REGROW_CHANCE = 0.10

-- 金丝雀稻草人吸引距离
TUNING.BIRD_CANARY_LURE_DISTANCE = 12
TUNING.BIRD_PERISH_TIME = TUNING.TOTAL_DAY_TIME * 5

-- 岩石通用
TUNING.ROCKS_MINE = TUNING.ROCKS_MINE or 6

-- 蘑菇帽孢子刷新
TUNING.MUSHROOMHAT_SPORE_TIME = seg_time * 2
TUNING.MUSHROOMHAT_SLOW_HUNGER = 0.75
TUNING.MUSHROOMHAT_MOONSPORE_TIME = 1.5
TUNING.MUSHROOMHAT_MOONSPORE_TIME_VARIANCE = 0.25

-- 植物怪物通用
TUNING.PLANTMOB_BURNTIME_MULT = 4/3
TUNING.PLANTMOB_FIRE_DAMAGE_SCALE = 1.25

----------------<火龙果蝾螈 Fruit Dragon TUNING>----------------
TUNING.FRUITDRAGON = {
    HEALTH = 50,
    RUN_SPEED = 6,
    WALK_SPEED = 3,
    ATTACK_PERIOD = 2,
    ATTACK_RANGE = 2,
    HIT_RANGE = 1.5,
    RIPE_DAMAGE = 20,
    UNRIPE_DAMAGE = 10,
    -- 作息
    AWAKE_TIME_MIN = 40,
    AWAKE_TIME_VAR = 20,
    AWAKE_TIME_RIPE_MOD = 0.67,
    AWAKE_TIME_HOMELESS_MOD = 0.5,
    NAP_TIME_MIN = 30,
    NAP_TIME_VAR = 15,
    NAP_TIME_RIPE_MOD = 0.67,
    NAP_TIME_HOMELESS_MOD = 1.5,
    -- 热源
    NAP_DIST_FROM_HOME = 6,
    NAP_MIN_HEAT = 15,
    RIPEN_NAP_MIN_HEAT = 40,
    -- 回血
    NAP_REGEN_AMOUNT = 2,
    NAP_REGEN_INTERVAL = 5,
    -- 找家
    FIND_HOME_RANGE = 15,
    ENTITY_SLEEP_FIND_HOME_RANGE = 15,
    KEEP_HOME_RANGE = 10,
    -- 挑战
    CHALLENGE_DIST = 15,
    CHALLENGE_WIN_CHANCE = 0.3,
    CHALLENGE_LOST_PANIC_TIME = 15,
    -- 火焰攻击
    FIREATTACK_COOLDOWN = 6,
    FIREATTACK_HIT_RANGE = 3,
    FIREATTACK_DAMAGE = 30,
}

-- 毒菌蛤蟆
TUNING.TOADSTOOL_HEALTH = 7500
TUNING.TOADSTOOL_ATTACK_RANGE = 7
TUNING.TOADSTOOL_EPICSCARE_RANGE = 10
TUNING.TOADSTOOL_DEAGGRO_DIST = 25
TUNING.TOADSTOOL_AGGRO_DIST = 15
TUNING.TOADSTOOL_RESPAWN_TIME = total_day_time * 20
TUNING.TOADSTOOL_SPAWN_TIME = 10
TUNING.SPAWN_TOADSTOOL = true

TUNING.TOADSTOOL_SPEED_LVL = { [0] = .6, [1] = .8, [2] = 1.2, [3] = 3.2 }
TUNING.TOADSTOOL_DAMAGE_LVL = { [0] = 100, [1] = 120, [2] = 150, [3] = 250 }
TUNING.TOADSTOOL_ATTACK_PERIOD_LVL = { [0] = 3.5, [1] = 3, [2] = 2.5, [3] = 2 }
TUNING.TOADSTOOL_ABSORPTION_LVL = { [0] = 0, [1] = .2, [2] = .4, [3] = .8 }
TUNING.TOADSTOOL_HIT_RECOVERY_LVL = { [0] = 1, [1] = 1.5, [2] = 2, [3] = 3 }

TUNING.TOADSTOOL_MUSHROOMBOMB_MIN_RANGE = 4
TUNING.TOADSTOOL_MUSHROOMBOMB_MAX_RANGE = 8.75
TUNING.TOADSTOOL_MUSHROOMBOMB_RADIUS = 3.5
TUNING.TOADSTOOL_MUSHROOMBOMB_CD = 5
TUNING.TOADSTOOL_MUSHROOMBOMB_COUNT_PHASE = { [1] = 4, [2] = 5, [3] = 6 }
TUNING.TOADSTOOL_MUSHROOMBOMB_VAR_LVL = { [0] = 0, [1] = 1, [2] = 2, [3] = 3 }
TUNING.TOADSTOOL_MUSHROOMBOMB_CHAIN_LVL = { [0] = 1, [1] = 2, [2] = 3, [3] = 5 }

TUNING.TOADSTOOL_SPOREBOMB_ATTACK_RANGE = 10
TUNING.TOADSTOOL_SPOREBOMB_HIT_RANGE = 14
TUNING.TOADSTOOL_SPOREBOMB_TIMER = 3.5
TUNING.TOADSTOOL_SPOREBOMB_TARGETS_PHASE = { [1] = 1, [2] = 2, [3] = 2 }
TUNING.TOADSTOOL_SPOREBOMB_CD_PHASE = { [1] = 14, [2] = 10, [3] = 10 }

TUNING.TOADSTOOL_SPORECLOUD_DAMAGE = 20
TUNING.TOADSTOOL_SPORECLOUD_ROT = .07
TUNING.TOADSTOOL_SPORECLOUD_RADIUS = 3.5
TUNING.TOADSTOOL_SPORECLOUD_TICK = 1
TUNING.TOADSTOOL_SPORECLOUD_LIFETIME = 60

TUNING.TOADSTOOL_MUSHROOMSPROUT_NUM = 4
TUNING.TOADSTOOL_MUSHROOMSPROUT_MIN_RANGE = 6
TUNING.TOADSTOOL_MUSHROOMSPROUT_MAX_RANGE = 10
TUNING.TOADSTOOL_MUSHROOMSPROUT_TICK = 2
TUNING.TOADSTOOL_MUSHROOMSPROUT_DURATION = 15
TUNING.TOADSTOOL_MUSHROOMSPROUT_CD = 45
TUNING.TOADSTOOL_MUSHROOMSPROUT_CHOPS = 10

TUNING.TOADSTOOL_POUND_CD = 20
TUNING.TOADSTOOL_ABILITY_INTRO_CD = 10

TUNING.TOADSTOOL_DARK_HEALTH = 99999
TUNING.TOADSTOOL_DARK_MUSHROOMSPROUT_CHOPS = 14
TUNING.TOADSTOOL_DARK_DAMAGE_LVL = { [0] = 150, [1] = 175, [2] = 225, [3] = 300 }
TUNING.TOADSTOOL_DARK_ABSORPTION_LVL = { [0] = 0, [1] = .25, [2] = .5, [3] = .99 }

-- 金丝雀
TUNING.BIRD_CANARY_LURE_DISTANCE = 12
TUNING.BIRD_PERISH_TIME = total_day_time * 5

TUNING.MUSHSPORE_PERISH_TIME = seg_time * 3
TUNING.MUSHSPORE_MAX_DENSITY = 10
TUNING.MUSHSPORE_MAX_DENSITY_RAD = 20
TUNING.MUSHSPORE_DENSITY_CHECK_TIME = 15
TUNING.MUSHSPORE_DENSITY_CHECK_VAR = 15

TUNING.MOONSPORE_ATTACK_RANGE = 3
TUNING.MOONSPORE_ATTACK_PROXIMITY = 3.5
TUNING.MOONSPORE_DAMAGE = 10
TUNING.MOONSPORE_PERISH_TIME = seg_time * 0.25

TUNING.MUSHROOMHAT_SPORE_TIME = seg_time * 2
TUNING.MUSHROOMHAT_SLOW_HUNGER = 0.75
TUNING.MUSHROOMHAT_MOONSPORE_TIME = 1.5
TUNING.MUSHROOMHAT_MOONSPORE_TIME_VARIANCE = 0.25
TUNING.MUSHROOMHAT_MOONSPORE_RETALIATION_SPORE_COUNT = 3
TUNING.MUSHROOMHAT_MOONSPORE_RETALIATION_SPORE_DELAY = 0.25

TUNING.PERISH_MUSHROOM_LIGHT_MULT = .25
TUNING.YELLOW_DART_DAMAGE = 60
TUNING.YELLOW_DART_DAMAGE_DS = 120

TUNING.EXPLOSIVE_MAX_RESIST_DAMAGE = 8000
TUNING.EXPLOSIVE_RESIST_DECAY_TIME = 8
TUNING.EXPLOSIVE_RESIST_DECAY_DELAY = 2
TUNING.EXPLOSIVE_MAX_WORKABLE_INVENTORYITEMS = 20

-- 无眼鹿（mushgnome用）
TUNING.SANITYAURA_SUPERHUGE = TUNING.SANITYAURA_SUPERHUGE or 100/(seg_time*.25)
TUNING.SANITYAURA_MED = TUNING.SANITYAURA_MED or -100/60
TUNING.SANITYAURA_SMALL = TUNING.SANITYAURA_SMALL or -50/60

----------------<档案馆生物 DUSTMOTH / ARCHIVE_CENTIPEDE TUNING>----------------
TUNING.DUSTMOTH =
{
    HEALTH = 200,
    HEALTH_REGEN = 4,
    WALK_SPEED = 2.6,
    DUSTABLE_RESET_TIME = seg_time * 2,
    DUSTABLE_RESET_TIME_VARIANCE = seg_time,
    DUSTOFF_COOLDOWN = 4,
    DUSTOFF_COOLDOWN_VARIANCE = 6,
    SEARCH_ANIM_COOLDOWN = 12,
    BLUEPRINT_DROP_CHANCE_REPEAT = 1.0,
}
TUNING.DUSTMOTHDEN_REPAIR_TIME = 10
TUNING.DUSTMOTHDEN_REGEN_TIME = total_day_time * 10
TUNING.DUSTMOTHDEN_RELEASE_TIME = seg_time
TUNING.DUSTMOTHDEN_MAX_CHILDREN = 1
TUNING.DUSTMOTHDEN_MAXWORK = 5
TUNING.DUSTMOTHDEN_ENABLED = true

----------------<蝙蝠洞 BATCAVE TUNING>----------------
TUNING.BATCAVE_REGEN_TIME = seg_time * 4
TUNING.BATCAVE_SPAWN_TIME = 20
TUNING.BATCAVE_MAX_CHILDREN = 4
TUNING.BATCAVE_ENABLED = true

TUNING.ARCHIVE_CENTIPEDE =
{
    DAMAGE = 40,
    AOE_DAMAGE = 20,
    HEALTH = 400 * 3,
    WALK_SPEED = 4,
    ATTACK_PERIOD = 5,
    ATTACK_RANGE = 3,
    HUSK_HEALTH = 300,
    AOE_RANGE = 4,
    TARGET_DIST = 24,
}

----------------<档案馆生物 DUSTMOTH / ARCHIVE_CENTIPEDE TUNING>----------------
TUNING.DUSTMOTH =
{
    HEALTH = 200,
    HEALTH_REGEN = 4,
    WALK_SPEED = 2.6,
    DUSTABLE_RESET_TIME = seg_time * 2,
    DUSTABLE_RESET_TIME_VARIANCE = seg_time,
    DUSTOFF_COOLDOWN = 4,
    DUSTOFF_COOLDOWN_VARIANCE = 6,
    SEARCH_ANIM_COOLDOWN = 12,
    BLUEPRINT_DROP_CHANCE_REPEAT = 1.0,
}
TUNING.DUSTMOTHDEN_REPAIR_TIME = 10
TUNING.DUSTMOTHDEN_REGEN_TIME = total_day_time * 10
TUNING.DUSTMOTHDEN_RELEASE_TIME = seg_time
TUNING.DUSTMOTHDEN_MAX_CHILDREN = 1
TUNING.DUSTMOTHDEN_MAXWORK = 5
TUNING.DUSTMOTHDEN_ENABLED = true

TUNING.ARCHIVE_CENTIPEDE =
{
    DAMAGE = 40,
    AOE_DAMAGE = 20,
    HEALTH = 400 * 3,
    WALK_SPEED = 4,
    ATTACK_PERIOD = 5,
    ATTACK_RANGE = 3,
    HUSK_HEALTH = 300,
    AOE_RANGE = 4,
    TARGET_DIST = 24,
}

--------------------------<archive_resonator>--------------------------
TUNING.ARCHIVE_RESONATOR = TUNING.ARCHIVE_RESONATOR or
{
    USES = 10,
}

----------------<vent 区内容 TUNING>----------------
-- 巨石枝 (tree_rock)
TUNING.TREE_ROCK = TUNING.TREE_ROCK or {
    CHOP = 5,
    MINE = 9,
    MINE_MED = 4,
    MINE_LOW = 2,
    AOE_DAMAGE = 150,
    ROCK1_AOE_RADIUS = 3.5,
    ROCK1_AOE_DAMAGE = 80,
    ROCK2_AOE_RADIUS = 2.5,
    ROCK2_AOE_DAMAGE = 60,
    BURN_TIME = 45,
    PLAYERDAMAGEPERCENT = 0.5,
    BOULDER_GEN_CHANCE = 1/3,
    GROW_TIME = {
        {base=3*seg_time, random=seg_time},
        {base=6*seg_time, random=2*seg_time},
    },
    SAPLING_GROW_TIME = {base=1200, random=300},
}
TUNING.TREE_ROCK_REGROWTH = TUNING.TREE_ROCK_REGROWTH or {
    OFFSPRING_TIME = total_day_time * 10,
    DESOLATION_RESPAWN_TIME = 480 * 50,
    DEAD_DECAY_TIME = 480 * 30,
}
TUNING.TREE_ROCK_REGROWTH_TIME_MULT = TUNING.TREE_ROCK_REGROWTH_TIME_MULT or 1
TUNING.LEIF_REAWAKEN_RADIUS = TUNING.LEIF_REAWAKEN_RADIUS or 20

-- 喷气孔 (cave_vent)
TUNING.CAVE_VENTS = TUNING.CAVE_VENTS or {
    MINE = 6,
    MINE_MED = 4,
    MINE_LOW = 2,
    SPEW_TIME = {
        HOT = { BASE = 20, VARIANCE = 5 },
        MIASMA = { BASE = 10, VARIANCE = 3 },
        GAS = { BASE = 15, VARIANCE = 5 },
    },
    HEAT = {
        HOT_ACTIVE = 70,
        MIASMA_ACTIVE = 65,
        COLD_ACTIVE = -10,
        INACTIVE = 10,
    },
}

-- 地热螨 (cave_vent_mite)
TUNING.CAVE_MITE_HEALTH = TUNING.CAVE_MITE_HEALTH or 200
TUNING.CAVE_MITE_DAMAGE = TUNING.CAVE_MITE_DAMAGE or 20
TUNING.CAVE_MITE_ATTACK_PERIOD = TUNING.CAVE_MITE_ATTACK_PERIOD or 3
TUNING.CAVE_MITE_WALK_SPEED = TUNING.CAVE_MITE_WALK_SPEED or 3
TUNING.CAVE_MITE_RUN_SPEED = TUNING.CAVE_MITE_RUN_SPEED or 5
TUNING.CAVE_MITE_TARGET_DIST = TUNING.CAVE_MITE_TARGET_DIST or 10
TUNING.CAVE_MITE_SPAWN_RADIUSSQ = TUNING.CAVE_MITE_SPAWN_RADIUSSQ or 225
TUNING.CAVE_MITE_RELEASE_TIME = TUNING.CAVE_MITE_RELEASE_TIME or 10
TUNING.CAVE_MITE_REGEN_TIME = TUNING.CAVE_MITE_REGEN_TIME or seg_time * 4
TUNING.CAVE_MITE_MAX_CHILDREN = TUNING.CAVE_MITE_MAX_CHILDREN or 4
TUNING.CAVE_MITE_ENABLED = TUNING.CAVE_MITE_ENABLED or true
TUNING.CAVE_MITE_SEE_FOOD_DIST = TUNING.CAVE_MITE_SEE_FOOD_DIST or 10
TUNING.CAVE_MITE_MAX_WANDER_DIST = TUNING.CAVE_MITE_MAX_WANDER_DIST or 20
TUNING.CAVE_MITE_DAMAGE_UNTIL_SHIELD = TUNING.CAVE_MITE_DAMAGE_UNTIL_SHIELD or 30
TUNING.CAVE_MITE_SHIELD_ATTACK_TIME = TUNING.CAVE_MITE_SHIELD_ATTACK_TIME or 5
TUNING.CAVE_MITE_MAX_CHASE_TIME = TUNING.CAVE_MITE_MAX_CHASE_TIME or 8
TUNING.CAVE_MITE_SHIELD_TIME = TUNING.CAVE_MITE_SHIELD_TIME or 8
TUNING.CAVE_MITE_SHIELD_TIME_VARIANCE = TUNING.CAVE_MITE_SHIELD_TIME_VARIANCE or 3
TUNING.CAVE_MITE_SHIELD_COOLDOWN = TUNING.CAVE_MITE_SHIELD_COOLDOWN or 10
TUNING.CAVE_MITE_SHIELD_COOLDOWN_VARIANCE = TUNING.CAVE_MITE_SHIELD_COOLDOWN_VARIANCE or 5
TUNING.CAVE_MITE_SHELL_ABSORB = TUNING.CAVE_MITE_SHELL_ABSORB or 0.75
TUNING.CAVE_MITE_BLOW_DISTANCE = TUNING.CAVE_MITE_BLOW_DISTANCE or 6
TUNING.CAVE_MITE_BLOW_DISTANCE_SQ_MIN = TUNING.CAVE_MITE_BLOW_DISTANCE_SQ_MIN or 1
TUNING.CAVE_MITE_BLOW_DISTANCE_SQ = TUNING.CAVE_MITE_BLOW_DISTANCE_SQ or 36
TUNING.CAVE_MITE_BLOW_COOLDOWN = TUNING.CAVE_MITE_BLOW_COOLDOWN or 8
TUNING.CAVE_MITE_BLOW_HEAT_RATE = TUNING.CAVE_MITE_BLOW_HEAT_RATE or { COLD = 8, HOT = 20, NORMAL = 12 }
TUNING.ACID_INFUSION_MULT = TUNING.ACID_INFUSION_MULT or { STRONGER = 2 }

-- 洞穴荧光花 (flower_cave)，仅枯萎变种使用
TUNING.FLOWER_CAVE_REGROW_TIME = TUNING.FLOWER_CAVE_REGROW_TIME or total_day_time
TUNING.FLOWER_CAVE_LIGHT_TIME = TUNING.FLOWER_CAVE_LIGHT_TIME or 30
TUNING.FLOWER_CAVE_RECHARGE_TIME = TUNING.FLOWER_CAVE_RECHARGE_TIME or 5
TUNING.FLOWER_CAVE_WITHERED_LIGHT_TIME = TUNING.FLOWER_CAVE_WITHERED_LIGHT_TIME or 15
TUNING.FLOWER_CAVE_WITHERED_RECHARGE_TIME = TUNING.FLOWER_CAVE_WITHERED_RECHARGE_TIME or 10

-- 光飞虫花 (lightflier_flower)
TUNING.LIGHTFLIER_FLOWER_REGROW_TIME = TUNING.LIGHTFLIER_FLOWER_REGROW_TIME or total_day_time * 3
TUNING.LIGHTFLIER_FLOWER_LIGHT_TIME = TUNING.LIGHTFLIER_FLOWER_LIGHT_TIME or 140
TUNING.LIGHTFLIER_FLOWER_LIGHT_TIME_VARIANCE = TUNING.LIGHTFLIER_FLOWER_LIGHT_TIME_VARIANCE or 50
TUNING.LIGHTFLIER_FLOWER_RECHARGE_TIME = TUNING.LIGHTFLIER_FLOWER_RECHARGE_TIME or 110
TUNING.LIGHTFLIER_FLOWER_TARGET_NUM_CHILDREN_OUTSIDE = TUNING.LIGHTFLIER_FLOWER_TARGET_NUM_CHILDREN_OUTSIDE or 1
TUNING.LIGHTFLIER_FLOWER_PICKABLE = true
TUNING.LIGHTFLIER_FLOWER_RECALL_DELAY = TUNING.LIGHTFLIER_FLOWER_RECALL_DELAY or 60
TUNING.LIGHTFLIER_FLOWER_RECALL_DELAY_VARIANCE = TUNING.LIGHTFLIER_FLOWER_RECALL_DELAY_VARIANCE or 60

----------------<梦魇疯猪 Daywalker TUNING>----------------
TUNING.DAYWALKER_HEALTH = TUNING.DAYWALKER_HEALTH or 10000
TUNING.DAYWALKER_HEALTH_REGEN = TUNING.DAYWALKER_HEALTH_REGEN or 25
TUNING.DAYWALKER_COMBAT_STALKING_HEALTH_REGEN = TUNING.DAYWALKER_COMBAT_STALKING_HEALTH_REGEN or 10
TUNING.DAYWALKER_COMBAT_TIRED_HEALTH_REGEN = TUNING.DAYWALKER_COMBAT_TIRED_HEALTH_REGEN or 20
TUNING.DAYWALKER_COMBAT_HEALTH_REGEN_PERIOD = TUNING.DAYWALKER_COMBAT_HEALTH_REGEN_PERIOD or 0.4
TUNING.DAYWALKER_WALKSPEED = TUNING.DAYWALKER_WALKSPEED or 2.7
TUNING.DAYWALKER_RUNSPEED = TUNING.DAYWALKER_RUNSPEED or 9
TUNING.DAYWALKER_HIT_RECOVERY = TUNING.DAYWALKER_HIT_RECOVERY or 1
TUNING.DAYWALKER_STALK_HIT_RECOVERY = TUNING.DAYWALKER_STALK_HIT_RECOVERY or 1.5
TUNING.DAYWALKER_DODGE_HIT_RECOVERY = TUNING.DAYWALKER_DODGE_HIT_RECOVERY or 2
TUNING.DAYWALKER_PILLAR_MINE = TUNING.DAYWALKER_PILLAR_MINE or 10
TUNING.DAYWALKER_RESPAWN_DAYS_COUNT = TUNING.DAYWALKER_RESPAWN_DAYS_COUNT or 10
TUNING.DAYWALKER_DAMAGE = TUNING.DAYWALKER_DAMAGE or 100
TUNING.DAYWALKER_STRUGGLE_DAMAGE = TUNING.DAYWALKER_STRUGGLE_DAMAGE or 34
TUNING.DAYWALKER_POUNCE_DAMAGE = TUNING.DAYWALKER_POUNCE_DAMAGE or 150
TUNING.DAYWALKER_XCLAW_DAMAGE = TUNING.DAYWALKER_XCLAW_DAMAGE or 75
TUNING.DAYWALKER_SLAM_DAMAGE = TUNING.DAYWALKER_SLAM_DAMAGE or 200
TUNING.DAYWALKER_ATTACK_RANGE = TUNING.DAYWALKER_ATTACK_RANGE or 5
TUNING.DAYWALKER_ATTACK_PERIOD = TUNING.DAYWALKER_ATTACK_PERIOD or { min = 2.5, max = 5 }
TUNING.DAYWALKER_STALK_CD = TUNING.DAYWALKER_STALK_CD or 36
TUNING.DAYWALKER_ROAR_CD = TUNING.DAYWALKER_ROAR_CD or 20
TUNING.DAYWALKER_AGGRO_DIST = TUNING.DAYWALKER_AGGRO_DIST or 20
TUNING.DAYWALKER_DEAGGRO_DIST = TUNING.DAYWALKER_DEAGGRO_DIST or 40
TUNING.DAYWALKER_KEEP_AGGRO_DIST = TUNING.DAYWALKER_KEEP_AGGRO_DIST or 50
TUNING.DAYWALKER_EPICSCARE_RANGE = TUNING.DAYWALKER_EPICSCARE_RANGE or 8
TUNING.DAYWALKER_SLAM_SINKHOLERADIUS = TUNING.DAYWALKER_SLAM_SINKHOLERADIUS or 3
TUNING.DAYWALKER_FATIGUE_REGEN = TUNING.DAYWALKER_FATIGUE_REGEN or 1
TUNING.DAYWALKER_FATIGUE_REGEN_PERIOD = TUNING.DAYWALKER_FATIGUE_REGEN_PERIOD or 0.5
TUNING.DAYWALKER_FATIGUE_REGEN_START_PERIOD = TUNING.DAYWALKER_FATIGUE_REGEN_START_PERIOD or 0
TUNING.DAYWALKER_FATIGUE_TIRED = TUNING.DAYWALKER_FATIGUE_TIRED or 9
TUNING.DAYWALKER_FATIGUE_TIRED_MIN_TIME = TUNING.DAYWALKER_FATIGUE_TIRED_MIN_TIME or 1.5
TUNING.DAYWALKER_FATIGUE_TIRED_MAX_TIME = TUNING.DAYWALKER_FATIGUE_TIRED_MAX_TIME or 5
TUNING.DAYWALKER_FATIGUE = TUNING.DAYWALKER_FATIGUE or { POUNCE_HIT = -2, POUNCE_MISS = 1.5, SLAM_HIT = -3 }
TUNING.SPAWN_DAYWALKER = TUNING.SPAWN_DAYWALKER or true
TUNING.DAYWALKER_SPAWN_NO_PLAYER_RADIUS = TUNING.DAYWALKER_SPAWN_NO_PLAYER_RADIUS or 35
TUNING.DAYWALKER_ARENA_RADIUS = TUNING.DAYWALKER_ARENA_RADIUS or (TILE_SCALE * 1.5)
TUNING.DAYWALKER_ARENA_CLEAR_RADIUS = TUNING.DAYWALKER_ARENA_CLEAR_RADIUS or (TILE_SCALE * 2.5)
TUNING.DAYWALKER_ARENA_PILLARS = TUNING.DAYWALKER_ARENA_PILLARS or 3
TUNING.SHADOW_LEECH_RUNSPEED = TUNING.SHADOW_LEECH_RUNSPEED or 6
TUNING.SHADOW_LEECH_HEALTH = TUNING.SHADOW_LEECH_HEALTH or 100

-- 绝望石装备 TUNING
TUNING.ARMORDREADSTONE = TUNING.ARMORDREADSTONE or 840
TUNING.ARMORDREADSTONE_ABSORPTION = TUNING.ARMORDREADSTONE_ABSORPTION or 0.9
TUNING.DREADSTONEHAT = TUNING.DREADSTONEHAT or 840
TUNING.DREADSTONEHAT_ABSORPTION = TUNING.DREADSTONEHAT_ABSORPTION or 0.9
TUNING.DREADSTONEHAT_WATERPROOFNESS = TUNING.DREADSTONEHAT_WATERPROOFNESS or 0.2
TUNING.ARMOR_DREADSTONE_REGEN_PERIOD = TUNING.ARMOR_DREADSTONE_REGEN_PERIOD or 1
TUNING.ARMOR_DREADSTONE_REGEN_MAXRATE = TUNING.ARMOR_DREADSTONE_REGEN_MAXRATE or 0.0667
TUNING.ARMOR_DREADSTONE_REGEN_MINRATE = TUNING.ARMOR_DREADSTONE_REGEN_MINRATE or 0.004
TUNING.ARMOR_DREADSTONE_REGEN_SETBONUS = TUNING.ARMOR_DREADSTONE_REGEN_SETBONUS or 2
TUNING.CRAZINESS_MED = TUNING.CRAZINESS_MED or (100/60)
TUNING.REPAIR_DREADSTONE_HEALTH = TUNING.REPAIR_DREADSTONE_HEALTH or 50
TUNING.DREADSTONEWALL_HEALTH = TUNING.DREADSTONEWALL_HEALTH or 350
TUNING.DREADSTONEWALL_WORK = TUNING.DREADSTONEWALL_WORK or 25
TUNING.DREADSTONEWALL_PLAYERDAMAGEMOD = TUNING.DREADSTONEWALL_PLAYERDAMAGEMOD or 0.25

----------------<暴动循环 Nightmare Cycle TUNING>----------------
-- 暴动各阶段段数（每段 = SEG_TIME 秒）
-- DST 默认：CALM=6, WARN=3, WILD=6, DAWN=3
TUNING.NIGHTMARE_SEGS = TUNING.NIGHTMARE_SEGS or {
    CALM = 0,
    WARN = 0,
    WILD = 99999,
    DAWN = 0,
}
-- 阶段时长随机偏移（单位：段）
TUNING.NIGHTMARE_SEG_VARIATION = TUNING.NIGHTMARE_SEG_VARIATION or 0
-- segment 秒数（DST 默认 30）
TUNING.SEG_TIME = TUNING.SEG_TIME or 30

----------------<档案馆安保 Archive Security TUNING>----------------
TUNING.ARCHIVE_SECURITY = TUNING.ARCHIVE_SECURITY or {
    REGEN_TIME = 120,
    RELEASE_TIME = 15,
    WALK_SPEED = 4,
}


